project:
  type: book
  output-dir: docs

lightbox: true

crossref:
  custom:
    - key: enr
      kind: float
      reference-prefix: "Enrichment topic"
    - key: lck
      kind: float
      reference-prefix: "Learning check"

book:
  title: "Lessons in Statistical Thinking"
  author: "Daniel Kaplan"
  date: "03/05/2024"
  cover-image: "www/signac.png"
  cover-image-alt: "Detail from Paul Signac, La Corne d’Or. 1907"
  repo-url: "https://github.com/dtkaplan/Lessons-in-statistical-thinking/"
  repo-actions: source

  chapters:
    - part: " "
    - index.qmd
    - part: Handling data
      chapters:
      - L01-Data-frames.qmd
      # - 115-Modeling-paradigm.qmd # deleted--- move to PRELUDE TO MODELING
      - L02-Pointplots.qmd
      - L03-Variation-and-distribution.qmd
      - L04-Model-annotations.qmd # 4
      - L05-Wrangling.qmd # chap 5
      - L06-Computing.qmd # chap 6
      - L07-Databases.qmd # chap 7
      # - 160-Projects-1.qmd # Maps, Census, Literature
    #######
    - part:  Describing relationships
      chapters:
      - L08-Statistical-thinking.qmd # chap 8 @sec-variation
      - L09-Accounting-for-variation.qmd # chap 9 @sec-accounting-for-variation
      - L10-Model-patterns.qmd # chap 10 @sec-model-patterns
      - L11-Regression.qmd # chap 11 @sec-regression
      - L12-Adjustment.qmd # chap 12 @sec-adjustment
    ########
    - part: Randomness and noise
      chapters:
      - L13-Signal-and-noise.qmd # chap 13# From Lesson 21
      - L14-Simulation.qmd # chap 14
      - L15-Noise-patterns.qmd # chap 15
      # 340-Probability-models has been replace by Noise-patterns
      # But there might be some material useful for examples.
      - L16-Estimation-and-likelihood.qmd # chap 16
      # - 355-Non-independence-and-extremes.qmd
      # - 340-Noise-patterns.qmd # mainly from Math 356 book
      - L17-R-squared.qmd # chap 17 Ch 28
      - L18-Prediction.qmd # ch. 18 # Lessons 25 & 26
      - L19-Sampling-variation.qmd # chap 19 # From Lesson 22
      - L20-Confidence-intervals.qmd # chap 20 # From Lesson 23
      - L21-Measuring-and-accumulating-risk.qmd # Ch 21
    ########
    - part: Causal modeling
      chapters:
      - L22-Effect-size.qmd # Ch. 22 # From Lesson 24
      - L23-DAGs.qmd # chap 23  Maybe move this to the Causal modeling part
      - L24-Causality-and-DAGS.qmd # Ch 24 # @sec-dag-causality
      - L25-Confounding.qmd # Ch 25 # From Lesson 30
      - L26-Experiment.qmd # Ch 26
      # - 465-Spurious-correlation.qmd # Ch 27 # DO I NEED THIS? Maybe as exercises
    ########
    - part: Hypothetical Thinking
      chapters:
      - L27-Hypothetical-thinking.qmd
      - L28-Bayes.qmd # Ch 28
      - L29-NHT.qmd # Ch 29
    - part: Appendices
      chapters:
      - Glossary.qmd

    #    - Draft-Exercises.qmd
    # - part: Statistical Thinking
    #   chapters:
    #     - Lesson-19.qmd
    #     - Lesson-20.qmd
    #     - Lesson-21.qmd
    #     - Lesson-22.qmd
    #     - Lesson-23.qmd
    #     - Lesson-24.qmd
    #     - Lesson-25.qmd
    #     - Lesson-26.qmd
    #     - Exercises/QR1.qmd
    #     - Lesson-28.qmd
    #     - Lesson-29.qmd
    #     - Lesson-30.qmd
    #     - Lesson-31.qmd
    #     - Lesson-32.qmd
    #     - Lesson-33.qmd
    #     - Lesson-34.qmd
    #     - Lesson-35.qmd ## need another class day for 34 and 35
    #     - Lesson-36.qmd
    #     - Lesson-37.qmd
    #     - Lesson-38.qmd
    #     - Exercises/QR2.qmd
    # - part: Appendices
    #  chapters:
    # #  - Software-appendix.qmd
    #  - Important-word-pairs.qmd
    #  - Projects/1940Census/Census-student-notes.Rmd
    # # - More-detail.qmd


format:
  html:
    number-depth: 1
    theme: flatly
    css: styles.css
    df-print: kable
    grid:
      margin-width: 400px
      body-width: 650px
      sidebar-width: 150px
  pdf:
    documentclass: default
    include-in-header:
      - latex-macros.tex

# Enable webR
webr:
  channel-type: 'automatic'
  packages: ['ggplot2', 'dplyr', 'LSTbook', 'ggformula', 'mosaicData', 'moderndive', 'palmerpenguins', 'babynames', 'knitr', 'rmarkdown', 'stringdist' ]
filters:
  - webr
