## Exercises


`r this_exercise(ID="Q24-1")`
{{< include ../LSTexercises/Lesson-24/Q24-1.Rmd >}}

::: {.callout-note collapse="true"}
`r this_exercise(ID="Q21-2")`
{{< include ../LSTexercises/Lesson-21/Q21-2.Rmd >}}
:::

::: {.callout-note collapse="true"}
`r this_exercise(ID="Q24-2")`
{{< include ../LSTexercises/Lesson-24/Q24-2.Rmd >}}
:::


::: {.callout-note collapse="true"}
`r this_exercise(ID="Q24-7")`
{{< include ../LSTexercises/Lesson-24/Q24-7.Rmd >}}
:::

::: {.callout-note collapse="true"}
`r this_exercise("regression-coefs-bird")`
:::

::: {.callout-note collapse="true"}
`r this_exercise(ID="Q21-4")`
{{< include ../LSTexercises/Lesson-21/Q21-4.Rmd >}}
:::



## Additional topics

::: {.callout-note collapse="true" icon="false"}
`r enrichment_topic(ID="Topic11-05", label="Regression to the mean")`
{{< include ../LSTexercises/11-Regression/Topic11-05.Rmd >}}
:::



::: {.callout-note collapse="true" icon="false"}
`r enrichment_topic(ID="Topic11-01", type = "Draft", label="Correlation and its coefficient")`
{{< include ../LSTexercises/11-Regression/Topic11-01.Rmd >}}
:::

::: {.callout-note collapse="true"}
`r enrichment_topic(ID="Topic11-02", type = "Draft", label="Curvey models")`
{{< include ../LSTexercises/11-Regression/Topic11-02.Rmd >}}
:::

::: {.callout-note collapse="true"}
`r enrichment_topic(ID="Topic11-03", type = "Draft", label="Too miscellaneous")`
{{< include ../LSTexercises/11-Regression/Topic11-03.Rmd >}}
:::

::: {.callout-note collapse="true"}
`r enrichment_topic(ID="Topic11-04", type = "Draft", label="Spurious correlation")`
{{< include ../LSTexercises/11-Regression/Topic11-04.Rmd >}}
:::



## Short projects

::: {.callout-note collapse="true"}
`r this_exercise(ID="Q24-3", type = "Project")`
{{< include ../LSTexercises/Lesson-24/Q24-3.Rmd >}}
:::

::: {.callout-note collapse="true"}
`r this_exercise(ID="Q24-4", type = "Project")`
{{< include ../LSTexercises/Lesson-24/Q24-4.Rmd >}}
:::



## Draft exercises





::: {.callout-note collapse="true"}
`r this_exercise(ID="Q11-105")`
{{< include ../LSTexercises/11-Regression/Q11-105.Rmd >}}
:::

::: {.callout-note collapse="true"}
`r this_exercise(ID="Q11-104")`
{{< include ../LSTexercises/11-Regression/Q11-104.Rmd >}}
:::

::: {.callout-note collapse="true"}
`r this_exercise(ID="Q11-103")`
{{< include ../LSTexercises/11-Regression/Q11-103.Rmd >}}
:::

::: {.callout-note collapse="true"}
`r this_exercise(ID="Q11-102")`
{{< include ../LSTexercises/11-Regression/Q11-102.Rmd >}}
:::

::: {.callout-note collapse="true"}
`r this_exercise(ID="Q11-101")`
{{< include ../LSTexercises/11-Regression/Q11-101.Rmd >}}
:::

::: {.callout-note collapse="true"}
`r this_exercise(ID="Q11-8")`
{{< include ../LSTexercises/11-Regression/Q11-108.Rmd >}}
:::

::: {.callout-note collapse="true"}
`r this_exercise(ID="Q11-9")`
{{< include ../LSTexercises/11-Regression/Q11-109.Rmd >}}
:::

::: {.callout-note collapse="true"}
`r this_exercise(ID="Q11-10")`
{{< include ../LSTexercises/11-Regression/Q11-110.Rmd >}}
:::

::: {.callout-note collapse="true"}
`r this_exercise(ID="Q11-11")`
{{< include ../LSTexercises/11-Regression/Q11-111.Rmd >}}
:::
