
## Exercises

## Draft exercises

::: {.callout-note collapse}
`r this_exercise("bayes-new-driver")`


DRAFT

A new driver has just gotten her license and wants to arrange car insurance. In order to set the premium (price of insurance), the insurance company needs an estimate of the accident risk.

At the start, it reasonable to assume a relatively high risk (per mile). USE THIS TO FORM A PRIOR, then multiply it by the likelihood of not being in an accident for the miles driven in the first year.
:::

::: {.callout-note collapse="true"}
Apply the formula for the posterior probability for many formulas for a situation where $N=2$: just two hypotheses. Derive the posterior odds formula from the posterior probability formula.

Hint: When there are just two hypotheses in play, ${\cal H_1}$ and ${\cal H_2}$, then, with priors and posteriors expressed as probabilities,

$$prior({\cal H_2}) = 1 - prior( \cal H_1)$$ and

$$posterior({\cal H_2}) = 1 - posterior( \cal H_1)$$
:::

::: {.callout-warning}
`r this_exercise("DRAFT-bayes-odds-form")`
{{< include ../LSTexercises/fromSummerDraft/bayes-odds-form.qmd >}}

:::

::: {.callout-note collapse="true"}
`r this_exercise(ID="Q33-4")`
{{< include ../LSTexercises/Lesson-33/Q33-4.Rmd >}}
:::

::: {.callout-note collapse="true"}
`r this_exercise(ID="DRAFT-Q34-1")`
{{< include ../LSTexercises/Lesson-34/Q34-1.Rmd >}}
:::

## Short projects

::: {.callout-note collapse="true"}
`r this_exercise(ID="Q34-2", type = "project")`
{{< include ../LSTexercises/Lesson-34/Q34-2.Rmd >}}
:::

::: {.callout-note collapse="true"}
`r this_exercise(ID="Q35-2", type = "project")`
{{< include ../LSTexercises/Lesson-35/Q35-5.Rmd >}}
:::

::: {.callout-note collapse="true"}
`r this_exercise(ID="Q28-303", type = "project")`
{{< include ../LSTexercises/28-Bayes/Q28-303.Rmd >}}
:::

::: {.callout-note collapse="true"}
`r this_exercise(ID="Q28-304", type = "project")`
{{< include ../LSTexercises/28-Bayes/Q28-304.Rmd >}}
:::

