

## Exercises

::: {.callout-note collapse="true"}
`r this_exercise(ID="Q36-2")`
{{< include ../LSTexercises/Lesson-36/Q36-2.Rmd >}}
:::


::: {.callout-note collapse="true"}
`r this_exercise(ID="DRAFT-Q36-1")`
{{< include ../LSTexercises/Lesson-36/Q36-1.Rmd >}}
:::

::: {.callout-note collapse="true"}
`r this_exercise(ID="Q36-4")`
{{< include ../LSTexercises/Lesson-36/Q36-4.Rmd >}}
:::

::: {.callout-note collapse="true"}
`r this_exercise(ID="Q29-101")`
{{< include ../LSTexercises/29-NHT/Q29-101.rmd}}
:::


## Draft exercises

::: {.callout-note collapse="true"}
`r this_exercise("Q29-201")`
{{< include ../LSTexercises/29-NHT/Q29-201.rmd}}
:::

::: {.callout-note collapse="true"}
`r this_exercise("Q29-202")`
{{< include ../LSTexercises/29-NHT/Q29-202.rmd}}
:::

::: {.callout-note collapse="true", type = "draft"}
`r this_exercise(ID="Q36-6")`

Write a problem based on $\chi^2$ and McNemar's test: <https://en.wikipedia.org/wiki/McNemar's_test>
:::


::: {.callout-note}
## Draft

The F statistic as SNR multiplied by the amount of data per parameter. This is useful for determining whether there is some discernible signal, but not whether the signal is intelligible for any particular purpose.
:::

## Short projects

::: {.callout-note collapse="true"}
`r this_exercise(ID="Q36-1", type = "project")`
{{< include ../LSTexercises/Lesson-36/Q36-1.Rmd >}}
:::

::: {.callout-note collapse="true"}
`r this_exercise(ID="Q36-3", type = "project")`
{{< include ../LSTexercises/Lesson-36/Q36-3.Rmd >}}
:::

::: {.callout-note collapse="true"}
`r this_exercise("Q29-301")`
{{< include ../LSTexercises/29-NHT/Q29-301.rmd}}
:::


## Additional topics

::: {.callout-note collapse="true"}
## p-value on R^2^
:::

::: {.callout-note collapse="true"}
P-hacking
:::

::: {.callout-note collapse="true"}
False discovery rate
:::


::: {.callout-note collapse="true"}
## Putting p-values in their place

:::


::: {.callout-note collapse="true"}
`r this_exercise("Q29-401")`
{{< include ../LSTexercises/29-NHT/Q29-401.rmd}}
:::

::: {.callout-note collapse="true"}
`r this_exercise("Q29-402")`
{{< include ../LSTexercises/29-NHT/Q29-402.rmd}}
:::

::: {.callout-note collapse="true"}
`r this_exercise("Q29-403")`
{{< include ../LSTexercises/29-NHT/Q29-403.rmd}}
:::

::: {.callout-note collapse="true"}
`r this_exercise("Q29-404")`
{{< include ../LSTexercises/29-NHT/Q29-404.rmd}}
:::

::: {.callout-note collapse="true"}
`r this_exercise("Q29-405")`
{{< include ../LSTexercises/29-NHT/Q29-405.rmd}}
:::

::: {.callout-note collapse="true"}
`r this_exercise("Q29-406")`
{{< include ../LSTexercises/29-NHT/Q29-406.rmd}}
:::

::: {.callout-note collapse="true"}
`r this_exercise("Q29-407")`
{{< include ../LSTexercises/29-NHT/Q29-407.rmd}}
:::
::: {.callout-note collapse="true"}
`r this_exercise("Q29-408")`
{{< include ../LSTexercises/29-NHT/Q29-408.rmd}}
:::

::: {.callout-note collapse="true"}
`r this_exercise("Q29-409")`
{{< include ../LSTexercises/29-NHT/Q29-409.rmd}}
:::

::: {.callout-note collapse="true"}
`r this_exercise("Q29-410")`
{{< include ../LSTexercises/29-NHT/Q29-410.rmd}}
:::

::: {.callout-note collapse="true"}
`r this_exercise("Q29-411")`
{{< include ../LSTexercises/29-NHT/Q29-411.rmd}}
:::

::: {.callout-note collapse="true"}
`r this_exercise("Q29-412")`
{{< include ../LSTexercises/29-NHT/Q29-412.rmd}}
:::

::: {.callout-note collapse="true"}
`r this_exercise("Q29-413")`
{{< include ../LSTexercises/29-NHT/Q29-413.rmd}}
:::

::: {.callout-note collapse="true"}
`r this_exercise("Q29-414")`
{{< include ../LSTexercises/29-NHT/Q29-414.rmd}}
:::

::: {.callout-note collapse="true"}
`r this_exercise("Q29-415")`
{{< include ../LSTexercises/29-NHT/Q29-415.rmd}}
:::
