<!-- Topic28-04 -->
::: {.callout-note collapse="true" #enr-28-104}
## Prior for schizophrenia?

Being a statistician, I am often approached by friends or acquaintances who have recently gotten a "positive" result on a medical screening test, for example cholesterol testing or prostate-specific antigen (PSA). They want to know how likely it is that they have the condition---heart disease or prostate cancer---being screened for. Before I can answer, I have to ask them an important question: How did you come to have the test? I want to know if the test was done as part of a general screening or if the test was done because of some relevant symptoms.

To illustrate why the matters of symptoms is important, consider a real-world test for schizophrenia. 

In 1981, President Reagan was among four people shot by John Hinkley, Jr. as they were leaving a speaking engagement at a D.C. hotel. At trial, Hinckley's lawyer presented an "insanity" defense, there being a longstanding legal principle that only people in control of their actions can be convicted of a crime.

As part of the evidence, Hinkley's defense team sought to present a CAT scan showing atrophy in Hinkley's brain. About 30% of schizophrenics had such atrophy, compared to only 2% of the non-schizophrenic population. Both of these are *likelihoods*, that is, a probability of what's observed *given* the state of the subject.

A. Based on the above, do you think the CAT scan would be strong evidence of schizophrenia?

A proper calculation of the probability that a person with atrophy is schizophrenic depends on the *prevalence* of schizophrenia. This was estimated at about 1.5% of the US population.

Calculating the probability of the subject's state given the observation of atrophy involves comparing two quantities, both of which have the form of a likelihood times a prevalence.

- Evidence in favor of schizophrenia: 
$$\underbrace{30\%}_\text{likelihood} \times \underbrace{1.5\%}_\text{prevalence} = 0.45\%$$
- Evidence against schizophrenia:
$$\underbrace{2\%}_\text{likelihood} \times \underbrace{98.5\%}_\text{prevalence} = 1.97\%$$
The probability of schizophrenia given atrophy compares the evidence for schizophrenia to the total amount of evidence:
$$\frac{0.45\%}{1.97\% + 0.45\%} = 18.6\%\ .$$
Based just on the result of the test for atrophy, Hinkley was not very likely to be a schizophrenic.

This is where the "How did you come to have the test?" question comes in.

For a person without symptoms, the 18.6% calculation is on target. But Hinkley had very definite symptoms: he had attempted an assassination. (Also, Hinkley's motivation for the attempt was to impress actress Jody Foster, to "win your heart and live out the rest of my life with you.)

The prevalence of of schizophrenia among prisoners convicted of fatal violence is estimated at about 10 times that of the general population. Presumably, it is even higher among those prisoners who have other symptoms of schizophrenia.

B. Repeat the "evidence for" and "against" schizophrenia, but updated for a prevalence of 20% instead of the original 1.5%. Has this substantially change the calculated probability of schizophrenia?

Epilogue: Hinkley was found not guilty by virtue of insanity. He was given convalescent leave from the mental hospital in 2016 and released entirely in 2022.


Note: This question is based on a discussion in the July 1984 "Misapplications Reviews" column of *INTERFACES* **14(4):48-52.
<!-- See `~/Downloads/25060588.pdf`.-->
:::
