<!-- Topic28-01 -->
::: {.callout-note collapse="true" #enr-28-01}
## Where do priors come from?

The use of Bayes' Rule (formula [-@eq-bayes-rule-odds]) to transform a prior into a posterior based on the likelihood of observed data is a mathematically correct application of probability. It is used extensively in engineering, machine learning and artificial intelligence, and statistics, among other fields. [Some neuroscientists argue](https://pubmed.ncbi.nlm.nih.gov/18045002/) that neurons provide a biological implementation of an approximation to Bayes' Rule.

*The Theory That Would Not Die: How Bayes' Rule Cracked the Enigma Code, Hunted Down Russian Submarines, and Emerged Triumphant from Two Centuries of Controversy*, by Sharon Bertsch McGrayne, provides a readable history. As the last words in the book's title indicate, despite being mathematically correct, Bayes' Rule has been a focus of disagreement among statisticians. The disagreement created a schism in statistical thought. The *Bayesians* are on one side, the other side comprises the *Frequentists*.

The name "frequentist" comes from a sensible-sounding definition of probability as rooted in long-run counts ("frequencies") of the outcomes of random trials. A trivial example: the frequentist account of a coin flip is that the probability of heads is 1/2 because, if you were to flip a coin many, many times, you would find that heads come up about as often as tails. According to frequentists, a hypothesis is either true or false; there is no meaningful sense of the probability of a hypothesis because there is only one reality; you can't sample from competing realities.

The frequentists dominated the development of statistical theory through the 1950s. Most of the techniques covered in conventional statistics courses stem from frequentist theorizing. One of the most famous frequentist techniques is *hypothesis testing*, the subject of Lesson [-@sec-NHT].

Today, mainstream statisticians see the schism between Frequentists and Bayesians as an unfortunate chapter in statististical history and view hypothesis testing as a dubious way to engage scientific questions (albeit one that still has power, controversially, as a gateway to research publication).

Frequentists note that beliefs differ from one person to the next and that priors may have little or no evidence behind them. Bayesians acknowledge that beliefs differ, but point out that a person disagreeing with a conclusion based on a questionable prior can themselves propose an alternative prior and find the posterior that corresponds to this alternative. Indeed, as illustrated in @enr-28-03, one can offer a range of priors and let the accumulating evidence create a narrower set of posteriors.






Or, prior probability for a sports team that was no good last year, but has had an excellent first three games.

DRAFT: Disease prevalence, general accident rate, long-term weather or sports statistics.

:::
