<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.549">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Daniel Kaplan">

<title>Lessons in Statistical Thinking - 1&nbsp; Data frames</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./L02-Pointplots.html" rel="next">
<link href="./index.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./L01-Data-frames.html">Handling data</a></li><li class="breadcrumb-item"><a href="./L01-Data-frames.html"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Data frames</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Lessons in Statistical Thinking</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/dtkaplan/Lessons-in-statistical-thinking/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text"> </span></span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Handling data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L01-Data-frames.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Data frames</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L02-Pointplots.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data graphics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L03-Variation-and-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Variation and density, graphically</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L04-Model-annotations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Annotating point plots with a model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L05-Wrangling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Data wrangling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L06-Computing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Computing with functions and arguments</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L07-Databases.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Databases</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Describing relationships</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L08-Statistical-thinking.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Statistical thinking &amp; variation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L09-Accounting-for-variation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Accounting for variation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L10-Model-patterns.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Model patterns</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L11-Regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Model functions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L12-Adjustment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Adjustment</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">Randomness and noise</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L13-Signal-and-noise.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Signal and noise</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L14-Simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Simulation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L15-Noise-patterns.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Models for noise</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L16-Estimation-and-likelihood.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Estimation and likelihood</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L17-R-squared.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">R-squared and covariates</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L18-Prediction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Predictions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L19-Sampling-variation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Sampling and sampling variation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L20-Confidence-intervals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Confidence intervals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L21-Measuring-and-accumulating-risk.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Measuring and accumulating risk</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
 <span class="menu-text">Causal modeling</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L22-Effect-size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Effect size</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L23-DAGs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Directed acyclic graphs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L24-Causality-and-DAGS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Causal influence and DAGs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L25-Confounding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Confounding</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L26-Experiment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Experiment and random assignment</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
 <span class="menu-text">Hypothetical Thinking</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L27-Hypothetical-thinking.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Hypothetical thinking</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L28-Bayes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Competing hypotheses with Bayesian reasoning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L29-NHT.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Hypothesis testing</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#types-of-variables" id="toc-types-of-variables" class="nav-link active" data-scroll-target="#types-of-variables">Types of variables</a></li>
  <li><a href="#sec-codebook" id="toc-sec-codebook" class="nav-link" data-scroll-target="#sec-codebook">The codebook</a></li>
  <li><a href="#accessing-data-frames" id="toc-accessing-data-frames" class="nav-link" data-scroll-target="#accessing-data-frames">Accessing data frames</a></li>
  <li><a href="#sec-computing-data-frames" id="toc-sec-computing-data-frames" class="nav-link" data-scroll-target="#sec-computing-data-frames">Computing with data frames</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises">Exercises</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/dtkaplan/Lessons-in-statistical-thinking/blob/main/L01-Data-frames.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./L01-Data-frames.html">Handling data</a></li><li class="breadcrumb-item"><a href="./L01-Data-frames.html"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Data frames</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-data-frames" class="quarto-section-identifier"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Data frames</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>The origin of recorded history is, literally, data. Five-thousand years ago, in Mesopotamia, the climate was changing. Retreating sources of irrigation water called for an organized and coordinated response, beyond the scope of isolated clans of farmers. To provide this response, a new social structure – government – was established and grew. Taxes were owed and paid, each transaction recorded. Food grain had to be measured and stored, livestock counted, trades and shipments memorialized.</p>
<p>Writing emerged as the technological innovation to keep track of all this. We know this today because memoranda were incised by stylus on soft clay tablets and baked into permanence. When the records were no longer needed, they were recycled as building materials for the growing settlements and cities. Archaeologists started uncovering these tablets more than 100 years ago, spending decades to decipher the meaning of the stylus marks in clay.</p>
<p>The writing and record-keeping technology developed over time: knots in string, wax tablets, papyrus, vellum, paper, and computer memory. Making sense of the records has always required <em>literacy</em>, deciphering marks according to the system and language used to represent the writer’s intent. Today, in many societies, the vast majority of people have been taught to read and write their native language according to the accepted conventions.</p>
<div class="page-columns page-full"><p>Conventions of record keeping diverge from those of everyday language. For instance, financial transaction records must be guarded against error and fraud. Starting in the thirteenth century, financial accountants adopted a practice—double-entry bookkeeping—that has no counterpart in everyday language. </p><div class="no-row-height column-margin column-container"><span class="margin-aside">“<a href="https://en.wikipedia.org/wiki/Double-entry_bookkeeping">Double-entry bookkeeping</a>,” records <em>twice</em> in two different places, in the form of a credit to an account and a debit from another account.</span></div></div>
<p>Modern conventions make working with data more accessible and more reliable. Of primary interest to us in these <em>Lessons</em> is the organization provided by a “<strong>data frame</strong>,” a structure for holding data as exemplified in <a href="#fig-data-frame-schematic" class="quarto-xref">Figure&nbsp;<span>1.1</span></a>.</p>
<div class="cell page-columns page-full" data-layout-align="center">
<div class="cell-output-display page-columns page-full">
<div id="fig-data-frame-schematic" class="quarto-figure quarto-figure-center quarto-float anchored page-columns page-full" data-cap-location="margin" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-data-frame-schematic-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="www/data-frame-schematic.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="1207">
</div>
<figcaption class="quarto-float-caption-margin quarto-float-caption quarto-float-fig margin-caption" id="fig-data-frame-schematic-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.1: A data frame organizes observed facts into rows and columns. Each column is a <strong>variable</strong>. Each row is a <strong>specimen</strong>. Here, there are four variables and five specimens. — The display in <a href="#fig-data-frame-schematic" class="quarto-xref">Figure&nbsp;<span>1.1</span></a> shows a small part of a larger data frame holding observations collected by statistician Francis Galton in the 1880s. I will use this data frame repeatedly across these lessons because of the outsized historical role the data played in the development of statistical methodology. The context for the data collection was Galton’s attempt to quantify the heritability of biological traits. The particular trait of interest to Galton (probably because it is easily measured) is human stature. Galton recorded the heights of full-grown children and their parents.
</figcaption>
</figure>
</div>
</div>
</div>
<p>The row-and-column organization of a data frame is reminiscent of a spreadsheet. However, data frames have additional organizational requirements that typical spreadsheet software does not enforce. The term “<strong>tidy data</strong>” emphasizes that these requirements are being met.</p>
<ol type="1">
<li><p>Each variable must consist of the same kind of individual entries. For example, the <code>mother</code> variable consists of numbers: a quantity. In this case, the quantity is the mother’s height in inches. It would not be legitimate for an entry in <code>mother</code> to be a word or to be a height in meters or something else entirely, for instance, a blood pressure.</p></li>
<li><p>Each row represents an individual real-world entity. For the data frame shown in <a href="#fig-data-frame-schematic" class="quarto-xref">Figure&nbsp;<span>1.1</span></a>, each row corresponds to an individual, fully-grown child. We use the term “<strong>unit of observation</strong>” to refer to the <em>kind of entity</em> represented in each row. All rows in a data frame must be the same kind of unit of observation. It would not be legitimate for some rows to individual people while others refer to something different such as a house or family or country. If you wanted to record data on families, you would need to create a new data frame where the unit of observation is a family.</p></li>
</ol>
<p>We use the word “<strong>specimen</strong>” to refer to an individual instance of the unit of observation. A data frame is a collection of specimens. Each row represents a unique specimen.</p>
<p>The unit of observation in <a href="#fig-data-frame-schematic" class="quarto-xref">Figure&nbsp;<span>1.1</span></a> is a full-grown child. The fifth row in that data frame refers to a unique young woman in London in the 1880s (whose name is lost to history). By using the word “specimen” to refer to this woman, we do not mean to dehumanize her. However, we need a phrase that can be applied to a single row of any data frame, whatever its unit of observation might be: a shipping container, a blood sample, a day of ticket sales, and so on.</p>
<p>The collection of specimens comprised by a data frame is often a “<strong>sample</strong>” from a larger group of the units of observation. Galton did not measure the height of every fully-grown child in London, England, the UK, or the World. He collected a <em>sample</em> from London families. Sometimes, a data frame includes every possible instance of the unit of observation. For example, a library catalog lists comprehensively the books in a library. Such a comprehensive collection is called a “<strong>census</strong>.”</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example: New-born babies
</div>
</div>
<div class="callout-body-container callout-body">
<p>The US Centers for Disease Control (CDC) publishes a “public use file” each year, a data frame where the unit of observation is an infant born in the US. (The many variables include the baby’s weight and sex, the mother’s age, and the number of prenatal care visits during the pregnancy.) The published file for 2022 contains 3,699,040 rows; that is the number of (known) births in 2022. As such, the CDC data constitutes a <strong>census</strong> rather than a <strong>sample</strong>.</p>
</div>
</div>
<section id="types-of-variables" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="types-of-variables">Types of variables</h2>
<p>Each column of a data frame is a variable. The word “variable” is appropriate because the entries within a variable <strong>vary</strong> one from one row to another. Other words with the same root include “variation,” “variety,” and even “diversity.”</p>
<p>Data-frame variables come in two fundamental types:</p>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="margin-aside">The distinction between quantitative and categorical variables is fundamental to statistical work. You should be able to discern whether a variable is categorical or quantitative from a glance at a data frame.</span></div></div>
<ol type="1">
<li><p><strong>Quantitative</strong> variables record an “amount” of something. These might just as well be called “numerical” variables.</p></li>
<li><p><strong>Categorical</strong> variables typically consist of letters. For instance, the <code>sex</code> variable in <a href="#fig-data-frame-schematic" class="quarto-xref">Figure&nbsp;<span>1.1</span></a> contains entries that are either <strong>F</strong> or <strong>M</strong>. In most of the data we work with in these <em>Lessons</em>, there is a fixed set of entry values called the <strong>levels</strong> of the categorical variable. The levels of <code>sex</code> are <strong>F</strong> and <strong>M</strong>.</p></li>
</ol>
<div class="page-columns page-full"><p></p><div class="no-row-height column-margin column-container"><span class="margin-aside">We are not doing full justice to the variety of possible variable types by focusing on just two type: quantitative and categorical. You should be aware that there are other kinds, for example, photographs or dates.</span></div></div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example (cont.): The CDC births data frame
</div>
</div>
<div class="callout-body-container callout-body">
<p>Among the many variables in the CDC public use file of births are <code>place</code> and <code>diabetes_gest</code>, which record the place of birth and whether the mother developed gestational diabetes.</p>
<p>The <code>place</code> variable is categorical, with these levels:</p>
<ul>
<li>“hospital”</li>
<li>“home (intended)”</li>
<li>“home (unintended)”</li>
<li>“freestanding”</li>
<li>“other”</li>
</ul>
<p>The <code>diabetes_gest</code> variable has two levels: <strong>N</strong> or <strong>Y</strong>.</p>
</div>
</div>
</section>
<section id="sec-codebook" class="level2">
<h2 class="anchored" data-anchor-id="sec-codebook">The codebook</h2>
<p>How are you to know for any given data frame what constitutes the unit of observation or what each variable is about? This information, sometimes called <strong>metadata</strong>, is stored outside the data frame. Often, the metadata is contained in a separate documentation file called a “<strong>codebook</strong>.”</p>
<p>To start, the codebook should make clear what is the unit of observation for the data frame. For instance, we described the unit of observation for the data frame shown in <a href="#fig-data-frame-schematic" class="quarto-xref">Figure&nbsp;<span>1.1</span></a> as a fully grown child. This detail is important. For instance, each such child—each specimen—can appear only once in the data frame. In contrast, the same <code>mother</code> and <code>father</code> might appear for multiple specimens, namely, the siblings of the child.</p>
<p>In the CDC data frame, the unit of observation is a newborn baby. If a birth resulted in twins, each of the two babies will have its own row. In contrast, imagine a data frame for the birth mothers or another for prenatal care visits. Each mother could appear only once in the birth-mothers frame, but the same mother can appear multiple times in the prenatal care data frame.</p>
<p>For quantitative variables, the relevant metadata includes what the number refers to (e.g., mother’s height or baby’s weight) and the physical units of that quantity (e.g., inches for height or grams for weight).</p>
<p>For categorical variables, the metadata should describe the meaning of each level in as much detail as necessary.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Example (cont.): CDC births codebook
</div>
</div>
<div class="callout-body-container callout-body">
<p>The codebook for the CDC data is a PDF document entitled “User Guide to the 2022 Natality Public Use File.” You can access it on the <a href="https://ftp.cdc.gov/pub/Health_Statistics/NCHS/Dataset_Documentation/DVS/natality/UserGuide2022.pdf">CDC website</a>.</p>
</div>
</div>
</section>
<section id="accessing-data-frames" class="level2">
<h2 class="anchored" data-anchor-id="accessing-data-frames">Accessing data frames</h2>
<p>Most statistics software, including R, makes it easy to access data frames stored as files in any of a variety of formats. (For examples, see <no exercise="" found="" under="" id="Q01-107">.)</no></p>
<p>Almost all the data frames used as examples or exercises in these <em>Lessons</em> are stored in files provided by R software “<strong>packages</strong>” such as <code>{LSTbook}</code> or <code>{mosaicData}</code>. The data frame itself is easily accessed by a simple name, e.g., <code>Galton</code>. The location of the data frame is specified by the package name as a prefix followed by a pair of colons, e.g.&nbsp;<code>mosaicData::Galton</code>. A convenient feature of this system is the easy access to documentation by giving a command consisting of a question mark followed by the <em>package-name</em>::<em>data-frame-name</em>, e.g.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>?mosaicData<span class="sc">::</span>Galton</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="sec-computing-data-frames" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="sec-computing-data-frames">Computing with data frames</h2>
<p>Lessons <a href="L02-Pointplots.html" class="quarto-xref"><span>2</span></a>, <a href="L03-Variation-and-distribution.html" class="quarto-xref"><span>3</span></a> &amp; <a href="L04-Model-annotations.html" class="quarto-xref"><span>4</span></a> cover how to make informative graphics that give an overview of the contents in a data frame. Lesson <a href="L05-Wrangling.html" class="quarto-xref"><span>5</span></a> introduces commands for manipulating the contents of a data frame to put them in a more useful form for the data graphics or data summary task at hand.</p>
<p>This Lesson shows you how to access data frames and their documentation and how to perform simple tasks such as listing the variable names or glimpsing a few rows of a data frame.</p>
<p>There are many software systems for working with data frames. Commonly available spreadsheet software, while suited to some data-entry and data-summarizing tasks, is surprisingly limited when it comes to statistical thinking. The system we will use, RStudio, is one of a handful used by data science professionals. It’s available free both as an online, browser-based platform and for installation on a laptop computer or computer server.</p>
<p>Much of the statistical work you do in RStudio consists of writing commands in the R language. The word “language” is offputting to many people, associating it as they do with natural languages such as Chinese or Spanish, mastery of which takes time and much work. Fortunately, you do not have to learn the R language; you need only a couple dozen R expressions to work through all these <em>Lessons</em>.</p>

<div class="no-row-height column-margin column-container"><div class="">
<p>If you are on your own, the instructions below provide a quick way to get started with minimal effort.</p>
<p>If you are a student using these Lessons as part of a class, check with your instructor who may already have set up a way for you to access RStudio.</p>
</div></div><p>We continue here under the assumption that you have already been shown how to install and access RStudio by an instructor or other mentor. That person will have arranged to install some additional software written for these <em>Lessons</em>, particularly the <code>{LSTbook}</code> package.</p>
<p>Each time you open RStudio, load the <code>{LSTbook}</code> package using this <strong>command</strong> at the R prompt in the “console” tab.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(LSTbook)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Starting out with R via <code>posit.cloud</code>
</div>
</div>
<div class="callout-body-container callout-body">
<p>Note: Otherwise …</p>
<p><code>posit.cloud</code> is a “freemium” web service. The word “freemium” signals that you can use it for free, up to a point. Fortunately, that point will suffice for you to follow all of these <em>Lessons</em>.</p>
<ol type="1">
<li>In your browser, follow <a href="https://posit.cloud/content/6532153">this link</a>. This will take you to <code>posit.cloud</code> and, after asking you to login via Google or to set up an account, will bring you to a page that will look much like the following. (It may take a few minutes.)</li>
</ol>
<p><img src="www/posit-cloud.png" class="img-fluid"></p>
<ol start="2" type="1">
<li><p>On the left half of the window, there are three “tabs” labelled “Console,” “Terminal,” and “Background Jobs.” You will be working in the “Console” tab. Click in that tab and you will see a flashing <code>|</code> cursor after the <code>&gt;</code> sign.</p></li>
<li><p>Give this command, exactly as written, and press return:</p></li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(LSTbook)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now you are ready to go.</p>
</div>
</div>
<p>All of your work with R will consist of giving commands at the <code>&gt;</code> prompt and pressing return. Possibly the simplest of all commands is merely the name of a data frame. For instance, the <code>{LSTbook}</code> package provides, among many others, a data frame named <code>AAUP</code>. Try this as a command:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>AAUP</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The result of such a command will be a print-out of the first several rows and columns of the data frame. Some of the data frames provided by <code>{LSTbook}</code> have a couple of dozen rows, others have tens of thousands. Printing out the first few rows of a data frame is useful since it shows the variable names and you can see whether each variable is quantitative or categorical.</p>
<p>To see the codebook for a data frame, simply precede the name with the <code>?</code> character, for instance:</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>?Births2022</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>

<div class="no-row-height column-margin column-container"><div id="fig-cdc-codebook" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cdc-codebook-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="www/births-documentation.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cdc-codebook-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.2: The codebook for the CDC births data frame can be accessed with <code>?Births2022</code>. When displayed in the RStudio Help tab, you can scroll through the descriptions of all 38 variables.
</figcaption>
</figure>
</div></div><p>RStudio arranges for the codebook to be displayed in the “Help” tab. This allows you to scroll through the documentation, follow web links (if any), and keep the names of the variables displayed in the Help tab while you write commands in the Console tab.</p>
<p>Commands you will use in these <em>Lessons</em> will often start with the name of a data frame followed a “<strong>pipeline</strong> symbol <code>|&gt;</code> which is then followed by a description of the action you want to perform. Let’s consider two simple actions:</p>
<ol type="1">
<li>Count the rows in the data frame:</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>AAUP <span class="sc">|&gt;</span> <span class="fu">nrow</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 28</code></pre>
</div>
</div>
<ol start="2" type="1">
<li>List the names of the variables.</li>
</ol>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>AAUP <span class="sc">|&gt;</span> <span class="fu">names</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "subject"  "acsal"    "fem"      "unemp"    "nonac"    "nonacsal" "licensed"</code></pre>
</div>
</div>
<p>These two commands have a similar structure involving four elements.</p>
<p><img src="www/latex-image-pipe.png" class="img-fluid"></p>
<!-- This doesn't render in the .html document, so I turned it into latex-image-pipe.png

$$\underbrace{\mathtt{AAUP}}_\text{name of data frame}\ \ \underbrace{\color{blue}{\texttt{|>}}}_\text{pipeline symbol} \ \ \underbrace{\texttt{nrow}}_\text{function name}\ \ \underbrace{\color{blue}{\texttt{()}}}_\text{open & close parentheses}$$ -->
<p>There are two names in this command: the name of a data frame and a “<strong>function</strong>” name. The function name is how you specify what you want to calculate from the data frame.</p>
<p>There are also two bits of punctuation:</p>
<ul>
<li><p>the pipeline symbol <code>|&gt;</code>, which connects the data frame to the function.</p></li>
<li><p>a pair of open and close parentheses immediately following the function name. Every time you use a function the function name will be followed by parentheses.</p></li>
</ul>
<div class="callout callout-style-default callout-note callout-titled page-columns page-full">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tables versus data frames
</div>
</div>
<div class="callout-body-container callout-body page-columns page-full">
<p>You may notice that the displays of data frames printed in this book are given labels such as <a href="#tbl-galton-dataframe" class="quarto-xref">Table&nbsp;<span>1.1</span></a>. It is natural to wonder why the word “table” is used sometimes and “data frame” other times.</p>
<p>In these <em>Lessons</em> we make the following distinction. A “data frame” stores values in the strict format of rows and columns described previously. Data frames are “machine readable.”</p>
<p>The data scientist working with data frames often seeks to create a <strong>display</strong> intended for human eyes. A “table” is one kind of <strong>display</strong> for humans. Since humans have common sense and have learned many ways to communicate with other humans, a table does not have to follow the restrictions placed on data frames. Tables are not necessarily organized in strict row-column format, can include units for numerical quantities and comments. An example is the table put together by Francis Galton (<a href="#fig-galton-notebook" class="quarto-xref">Figure&nbsp;<span>1.3</span></a>) to organize his measurements of heights.</p>
<div class="cell page-columns page-full">
<div class="cell-output-display page-columns page-full">
<div id="fig-galton-notebook" class="quarto-figure quarto-figure-center quarto-float anchored page-columns page-full" data-cap-location="margin">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-galton-notebook-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="www/galton-notebook-excerpt.png" class="img-fluid figure-img" width="588">
</div>
<figcaption class="quarto-float-caption-margin quarto-float-caption quarto-float-fig margin-caption" id="fig-galton-notebook-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.3: An excerpt from Francis Galton’s notebook recording the heights of parents and children in London in the 1880s.
</figcaption>
</figure>
</div>
</div>
</div>
<p>We make the distinction between a data frame (for data storage) and a table (for communicating with humans) because many of the operations discussed in later lessons serve the purpose of transforming data frames into human-facing displays such as graphics (Lesson <a href="L02-Pointplots.html" class="quarto-xref"><span>2</span></a>) or tables (<a href="L06-Computing.html#sec-displaying-tables" class="quarto-xref"><span>Section 6.7</span></a>.)</p>
<p>Often, a literal display of a data frame may seem inefficient, for instance this view of the <code>Galton</code> dataframe which was constructed from <a href="#fig-galton-notebook" class="quarto-xref">Figure&nbsp;<span>1.3</span></a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>Galton</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-and_so_on="... for 898 rows altogether">
<div id="tbl-galton-dataframe" class="cell quarto-float anchored" data-and_so_on="... for 898 rows altogether">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-galton-dataframe-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1.1: The records from the table shown in <a href="#fig-galton-notebook" class="quarto-xref">Figure&nbsp;<span>1.3</span></a> in a data-frame format.
</figcaption>
<div aria-describedby="tbl-galton-dataframe-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div style="font-family: Monospace;">
<table class="lightable-minimal do-not-create-environment cell table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">family</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">father</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">mother</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">sex</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">height</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">nkids</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: right;">78.5</td>
<td style="text-align: right;">67.0</td>
<td style="text-align: left;">M</td>
<td style="text-align: right;">73.2</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">1</td>
<td style="text-align: right;">78.5</td>
<td style="text-align: right;">67.0</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">69.2</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: right;">78.5</td>
<td style="text-align: right;">67.0</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">69.0</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">1</td>
<td style="text-align: right;">78.5</td>
<td style="text-align: right;">67.0</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">69.0</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2</td>
<td style="text-align: right;">75.5</td>
<td style="text-align: right;">66.5</td>
<td style="text-align: left;">M</td>
<td style="text-align: right;">73.5</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: right;">75.5</td>
<td style="text-align: right;">66.5</td>
<td style="text-align: left;">M</td>
<td style="text-align: right;">72.5</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2</td>
<td style="text-align: right;">75.5</td>
<td style="text-align: right;">66.5</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">65.5</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: right;">75.5</td>
<td style="text-align: right;">66.5</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">65.5</td>
<td style="text-align: right;">4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: right;">75.0</td>
<td style="text-align: right;">64.0</td>
<td style="text-align: left;">M</td>
<td style="text-align: right;">71.0</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">3</td>
<td style="text-align: right;">75.0</td>
<td style="text-align: right;">64.0</td>
<td style="text-align: left;">F</td>
<td style="text-align: right;">68.0</td>
<td style="text-align: right;">2</td>
</tr>
</tbody>
</table>

<span style="font-style: italic;">&nbsp; &nbsp; &nbsp; ... for 898 rows altogether</span>
</div>

</div>
</div>
</figure>
</div>
</div>
<p>It may seem that the data frame is inefficient, for example repeating the heights of mother and father for all the siblings in a family. But this view of efficiency relates to the use of paper and ink by a table; the computer entity requires a different view of efficiency.</p>
</div>
</div>
</section>
<section id="exercises" class="level2">
<h2 class="anchored" data-anchor-id="exercises">Exercises</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 1.1 bear-ride-pants
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The US Department of Transportation has a program called the Fatality Analysis Reporting System. FARS has a web site which publishes data. <a href="#fig-bear-ride-pants1" class="quarto-xref">Figure&nbsp;<span>1.4</span></a> shows a partial screen shot of their web page.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-bear-ride-pants1" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-bear-ride-pants1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="www/fars-1.png" class="img-fluid figure-img" width="368">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-bear-ride-pants1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.4: National statistics from the US on motor-vehicle accident-related fatalities. Source: <a href="https://www-fars.nhtsa.dot.gov/Main/index.aspx" class="uri">https://www-fars.nhtsa.dot.gov/Main/index.aspx</a>.
</figcaption>
</figure>
</div>
</div>
</div>
<p>For several reasons, the table is not in tidy form.</p>
<ol type="1">
<li><p>Some of the rows serve as headers for the next several rows, but don’t contain any data. Identify several of those headers. <span style="color: grey; font-style: italic;"><em>Answer</em>: “Motor vehicle traffic crashes”, “Traffic crash fatalities”, “Vehicle occupants”, “Non-motorists”, “Other national statistics”, “National rates: fatalities”</span></p></li>
<li><p>In tidy data, all the entries in a column should describe the same kind of quantity. You can see that all of the columns contain numbers. But the numbers are not all the same kind of quantity. Referring to the 2016 column:</p>
<ol type="a">
<li>What kind of thing is the number 34,439? <span style="color: grey; font-style: italic;"><em>Answer</em>: A number of crashes</span></li>
<li>What kind of thing is 18,610? <span style="color: grey; font-style: italic;"><em>Answer</em>: A number of drivers</span></li>
<li>What kind of thing is 1.18? <span style="color: grey; font-style: italic;"><em>Answer</em>: A rate: fatalities per 100-million miles.</span></li>
</ol></li>
<li><p>In tidy data, there is a definite unit of observation that is the same kind of thing for every row. Give an example of two rows that are not the same kind of thing. <span style="color: grey; font-style: italic;"><em>Answer</em>: For example, “Registered vehicles” and “Licensed drivers”. The first is a count of cars, the second a count of drivers.</span></p></li>
<li><p>Identify a few rows that are summaries of other rows. Such summaries are not themselves a unit of observation. <span style="color: grey; font-style: italic;"><em>Answer</em>: “Sub Total1”, “Sub Total2”, “Total**“</span></p></li>
</ol>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 1.2 camel-drive-roof
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>There are several small, example data frames in the <code>datasets</code> package. Look at the <code>Seatbelts</code> data frame using the <code>View()</code> function and the name of the object as an argument. You may also need to reference the documentation using <code>help()</code>. (Hint: refer to the data frame using the double-colon notation to include the package name, that is, <code>datasets::Seatbelts</code>.)</p>
<ul>
<li>What is the meaning of the <code>front</code> variable? <span style="color: grey; font-style: italic;"><em>Answer</em>: The number of front seat passengers killed or seriously injured.</span></li>
<li>How many specimens are there? <span style="color: grey; font-style: italic;"><em>Answer</em>: <code>nrow(Seatbelts)</code></span></li>
<li>What is the real-world meaning of a row, that is, what is the unit of observation? <span style="color: grey; font-style: italic;"><em>Answer</em>: A calendar month.</span></li>
</ul>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-8-contents" aria-controls="callout-8" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 1.3 cat-bring-shirt
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-8" class="callout-8-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>What’s not tidy about this table?</p>
<table class="table">
<thead>
<tr class="header">
<th><code>president</code></th>
<th><code>in office</code></th>
<th><code>number of states</code></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Lincoln, Abraham</td>
<td>1861-1865</td>
<td>it depends</td>
</tr>
<tr class="even">
<td>George Washington</td>
<td>1791-1799</td>
<td>16</td>
</tr>
<tr class="odd">
<td>Martin Van Buren</td>
<td>1837 to 1841</td>
<td>26</td>
</tr>
</tbody>
</table>
<p><em>Answer</em>:</p>
<div style="border-style: dotted; font-style: italic; margin-left: 1em;">
<p>The table would be tidier if …</p>
<ol type="1">
<li>The values of the <code>president</code> variable were all in the same form. As it is, the entry for Lincoln is in the form last-name, first-name, while the other values are not. It might also be appropriate to divide the name into two variables: given name and surname. For instance, “Van” is not the middle name of Martin Van Buren; it’s part of his surname “Van Buren.”</li>
<li>The <code>in office</code> variable contains two numbers, with different punctuation between them.<br>
</li>
<li>The <code>number of states</code> is not a number in Abraham Lincoln’s case. (The situation changed rapidly during the US Civil War.) All the values in a variable should be the same kind of thing.</li>
</ol>
<p>A bit more detail — one rule for tidy data is that all of the values for a variable should be the same kind of thing. You could argue that “1861-1865” and “1837 to 1841” are the same kind of thing: a set of characters that can be interpreted by a person. It’s much better, in general, if numerical quantities (like the year) are represented as numbers.</p>
</div>
<p>Re-write the table in a tidy form. Take care to render the information about years and about the number of states as numbers.</p>
<p><em>Answer</em>:</p>
<div style="border-style: dotted; font-style: italic; margin-left: 1em;">
<p>There are several reasonable possibilities, for instance:</p>
<table class="table">
<thead>
<tr class="header">
<th><code>first_name</code></th>
<th><code>last_name</code></th>
<th><code>start</code></th>
<th><code>end</code></th>
<th><code>n_states</code></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Abraham</td>
<td>Lincoln</td>
<td>1861</td>
<td>1865</td>
<td>26</td>
</tr>
<tr class="even">
<td>George</td>
<td>Washington</td>
<td>1791</td>
<td>1799</td>
<td>16</td>
</tr>
<tr class="odd">
<td>Martin</td>
<td>Van Buren</td>
<td>1837</td>
<td>1841</td>
<td>26</td>
</tr>
</tbody>
</table>
<p>In addition to the data table, the codebook could specify that <code>n_states</code> refers to the number of states when the President left office.</p>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-9-contents" aria-controls="callout-9" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 1.4 child-talk-candy
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-9" class="callout-9-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The codebook for several data tables relating to airports, airlines, and airline flights in the US is published in the <code>nycflights13</code> package. The documentation for the <code>airports</code> data frame from that package can be read <a href="https://rdrr.io/cran/nycflights13/man/airports.html">here</a>. According to the documentation:</p>
<ol type="1">
<li>How many variables are there?</li>
<li>What do the cases represent?</li>
<li>For each variable, make a reasonable guess about whether the values will be numerical or categorical.</li>
</ol>
<p><em>Answer</em>:</p>
<div style="border-style: dotted; font-style: italic; margin-left: 1em;">
<p>Each case is an airport. There are seven variables: <code>faa</code> (categorical), <code>name</code> (categorical), <code>lat</code> (numerical), <code>lon</code> (numerical), <code>alt</code> (numerical), <code>tz</code> (more or less numerical: data about times can be complicated), <code>dst</code> (categorical)</p>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-10-contents" aria-controls="callout-10" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 1.5 kangaroo-see-dress
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-10" class="callout-10-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The name of the <code>ggplot2::msleep</code> data frame doesn’t say much about the contents. Look at the documentation using the <code>?ggplot2::msleep</code> and with the <code>View(ggplot2::msleep)</code> to see the contents.</p>
<ul>
<li>What does the “m” in the name <code>msleep</code> refer to? <span style="color: grey; font-style: italic;"><em>Answer</em>: “m” as in “mammals.”</span></li>
<li>What is the meaning of the <code>brainwt</code> variable? <span style="color: grey; font-style: italic;"><em>Answer</em>: The help file specifies it as the “brain weight in kilograms.”</span></li>
<li>How many cases are there? <span style="color: grey; font-style: italic;"><em>Answer</em>: <code>nrow(msleep)</code></span></li>
<li>What is the real-world meaning of a case? <span style="color: grey; font-style: italic;"><em>Answer</em>: A kind of mammal, e.g.&nbsp;a biological genus and order.</span></li>
<li>What are the levels of the <code>vore</code> variable? <span style="color: grey; font-style: italic;"><em>Answer</em>: carni, omni, herbi, NA, insecti</span></li>
</ul>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-11-contents" aria-controls="callout-11" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 1.6 snake-come-closet
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-11" class="callout-11-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Look at the documentation for the <code>mosaicData::CPS85</code> data table. From reading that documentation, what is the meaning of “CPS”? <span style="color: grey; font-style: italic;"><em>Answer</em>: Current Population Survey</span></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-12-contents" aria-controls="callout-12" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 1.7 owl-say-knife
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-12" class="callout-12-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Here is an excerpt from the baby-name data set.</p>
<div class="cell" data-and_so_on="... and so on for 1924665 rows altogether.">
<div class="cell-output-display">
<div style="font-family: Monospace;">
<table class="lightable-minimal table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">year</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">sex</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">name</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">n</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">prop</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1970</td>
<td style="text-align: left;">F</td>
<td style="text-align: left;">Lakeitha</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">0.0000104</td>
</tr>
<tr class="even">
<td style="text-align: right;">1973</td>
<td style="text-align: left;">F</td>
<td style="text-align: left;">Helena</td>
<td style="text-align: right;">189</td>
<td style="text-align: right;">0.0001216</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1975</td>
<td style="text-align: left;">M</td>
<td style="text-align: left;">Torey</td>
<td style="text-align: right;">62</td>
<td style="text-align: right;">0.0000382</td>
</tr>
<tr class="even">
<td style="text-align: right;">1978</td>
<td style="text-align: left;">F</td>
<td style="text-align: left;">Cathrine</td>
<td style="text-align: right;">47</td>
<td style="text-align: right;">0.0000286</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1980</td>
<td style="text-align: left;">F</td>
<td style="text-align: left;">Enriqueta</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">0.0000045</td>
</tr>
<tr class="even">
<td style="text-align: right;">1982</td>
<td style="text-align: left;">F</td>
<td style="text-align: left;">Marelyn</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0.0000028</td>
</tr>
<tr class="odd">
<td style="text-align: right;">1984</td>
<td style="text-align: left;">M</td>
<td style="text-align: left;">Dimitrius</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">0.0000075</td>
</tr>
<tr class="even">
<td style="text-align: right;">1986</td>
<td style="text-align: left;">M</td>
<td style="text-align: left;">Penn</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">0.0000036</td>
</tr>
</tbody>
</table>

<span style="font-style: italic;">&nbsp; &nbsp; &nbsp; ... and so on for 1924665 rows altogether.</span>
</div>

</div>
</div>
<p>Consider these five entities, that appear in the table shown above (a) through (e):</p>
<ol type="a">
<li><code>Taffy</code> b) <code>year</code> c) <code>sex</code> d) <code>name</code> e) <code>n</code></li>
</ol>
<p>For each, choose one of the following:</p>
<ol type="1">
<li>It’s a categorical variable.</li>
<li>It’s a quantitative variable.</li>
<li>It’s the value of a variable for a particular case.</li>
</ol>
<p><em>Answer</em>:</p>
<div style="border-style: dotted; font-style: italic; margin-left: 1em;">
<p>Variable names always appear in the header of the data frame; values are the body of the frame.</p>
<ol type="1">
<li><code>Taffy</code> is a value, not a variable, so (3)</li>
<li><code>year</code> is quantitative, so (2)</li>
<li><code>sex</code> is categorical, so (1)</li>
<li><code>name</code> is categorical, so (1).</li>
<li><code>n</code> is quantitative, so (2).</li>
</ol>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-13-contents" aria-controls="callout-13" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 1.8 fox-fall-book
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-13" class="callout-13-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>List what’s not tidy about this table.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="www/planet-info.png" class="img-fluid figure-img" width="680"></p>
</figure>
</div>
</div>
</div>
<p><em>Answer</em>:</p>
<div style="border-style: dotted; font-style: italic; margin-left: 1em;">
<ul>
<li>Units ought to be in the codebook not the data frame.</li>
<li>The “length of year” variable is in a mixture of units. Some rows are (Earth) days, others are (Earth) years.</li>
<li>The numbers have commas, which are intended for human consumption. Data tables are for machine consumption and the commas are a nuisancwe.</li>
<li>The <span class="math inline">\(\frac{1}{4}\)</span> in the “length of year” column is not a standard computer numeral. Write 365.25 instead.</li>
</ul>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-14-contents" aria-controls="callout-14" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 1.9 pine-hit-pants
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-14" class="callout-14-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><a href="#tbl-pine-hit-pants" class="quarto-xref">Table&nbsp;<span>1.2</span></a> is a re-organization and simplification of the data in <a href="#fig-bear-ride-pants1" class="quarto-xref">Figure&nbsp;<span>1.4</span></a> (in Exercise Exercise 1.1) about motor-vehicle related fatalities in the US. (Only part of the data is shown.)</p>
<div class="cell" data-layout-align="FALSE">
<div id="tbl-pine-hit-pants" class="cell quarto-float anchored" data-layout-align="FALSE">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pine-hit-pants-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1.2: A reorganization of the data in <a href="#fig-bear-ride-pants1" class="quarto-xref">Figure&nbsp;<span>1.4</span></a>.
</figcaption>
<div aria-describedby="tbl-pine-hit-pants-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<div style="font-family: Monospace;">
<table class="lightable-minimal do-not-create-environment cell table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">year</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">crashes</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">drivers</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">passengers</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">unknown</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">miles</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">resident_pop</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">2016</td>
<td style="text-align: right;">34439</td>
<td style="text-align: right;">18610</td>
<td style="text-align: right;">6407</td>
<td style="text-align: right;">79</td>
<td style="text-align: right;">3174</td>
<td style="text-align: right;">323128</td>
</tr>
<tr class="even">
<td style="text-align: right;">2015</td>
<td style="text-align: right;">32539</td>
<td style="text-align: right;">17666</td>
<td style="text-align: right;">6213</td>
<td style="text-align: right;">71</td>
<td style="text-align: right;">3095</td>
<td style="text-align: right;">320897</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2014</td>
<td style="text-align: right;">30056</td>
<td style="text-align: right;">16470</td>
<td style="text-align: right;">5766</td>
<td style="text-align: right;">71</td>
<td style="text-align: right;">3026</td>
<td style="text-align: right;">318563</td>
</tr>
</tbody>
</table>
</div>
</div>
</div></figure>
</div>
</div>
<ol type="1">
<li>In the re-organized table, what is the unit of observation? <span style="color: grey; font-style: italic;"><em>Answer</em>: a year</span></li>
<li>Is the re-organized table tidy data?</li>
</ol>
<p><em>Answer</em>:</p>
<div style="border-style: dotted; font-style: italic; margin-left: 1em;">
<p>Yes. (a) There is a well-defined unit of observation that is the same kind of thing for each row. (b) The values for any given variable are also the same kind of thing. For instance, <code>drivers</code> is the number of drivers, <code>resident_pop</code> is the number of people in the national population.</p>
</div>
<ol start="3" type="1">
<li>For the purpose of this exercise, one of the numbers in <a href="#tbl-pine-hit-pants" class="quarto-xref">Table&nbsp;<span>1.2</span></a> has been copied with a small error. To see which it is, you’ll have to refer to <a href="#fig-bear-ride-pants1" class="quarto-xref">Figure&nbsp;<span>1.4</span></a>. Find that number and tell:
<ol type="a">
<li>In what year for <a href="#tbl-pine-hit-pants" class="quarto-xref">Table&nbsp;<span>1.2</span></a> does it appear? <span style="color: grey; font-style: italic;"><em>Answer</em>: 2015</span></li>
<li>In what variable for <a href="#tbl-pine-hit-pants" class="quarto-xref">Table&nbsp;<span>1.2</span></a> does it appear? <span style="color: grey; font-style: italic;"><em>Answer</em>: <code>drivers</code></span></li>
</ol></li>
<li>The quantity presented in the variable <code>miles</code> is not actually in miles. It has other units. Referring to <a href="#fig-bear-ride-pants1" class="quarto-xref">Figure&nbsp;<span>1.4</span></a> …
<ol type="a">
<li>What are the actual units? <span style="color: grey; font-style: italic;"><em>Answer</em>: Billions of miles.</span></li>
<li>Where should the information in (a) be documented? <span style="color: grey; font-style: italic;"><em>Answer</em>: In the meta-data (codebook) for the table.</span></li>
</ol></li>
</ol>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-15-contents" aria-controls="callout-15" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 1.10 lion-drink-sofa
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-15" class="callout-15-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The table below is a presentation intended for a human reader. Even though it is neatly organized, it is not <strong>tidy data</strong>.</p>
<div class="cell" data-layout-align="FALSE">
<div class="cell-output-display">
<div id="fig-shipping-losses" class="quarto-figure quarto-figure-center quarto-float anchored" data-fig-align="FALSE">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-shipping-losses-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="www/shipping-losses.png" class="img-fluid quarto-figure quarto-figure-FALSE figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-shipping-losses-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1.5: From W.S. Churchill (1952) <em>The Grand Alliance</em> a history of the Second World War. Houghton Mifflin Co.&nbsp;Boston. p.&nbsp;782
</figcaption>
</figure>
</div>
</div>
</div>
<ol type="1">
<li><p>In tidy data, each row must be the same kind of unit of analysis. Each row, but one, corresponds to a month of 1941. What is the row that is not a month of 1941? <span style="color: grey; font-style: italic;"><em>Answer</em>: “Totals” is not a month of the year.</span></p></li>
<li><p>Are the variable names unique? <span style="color: grey; font-style: italic;"><em>Answer</em>: There are four columns with the same title, “Gross Tons”. Similarly four columns are labelled “No.&nbsp;of Ships.” You could make the labels unique by prepending them with the terms “British,” “Allied,” and so on.</span></p></li>
<li><p>Two of the columns contain redundant data from the other columns. Which columns are these? <span style="color: grey; font-style: italic;"><em>Answer</em>: The total number of ships and total tons.</span></p></li>
<li><p>Imagine a data frame where the unit of observation is a ship.</p>
<ol type="a">
<li>How many rows would the data frame have? <span style="color: grey; font-style: italic;"><em>Answer</em>: 1141, the total number of ships.</span></li>
<li>What would the variables need to be in this imagined data frame in order to capture all of the data in the presentation table? <span style="color: grey; font-style: italic;"><em>Answer</em>: Ship tonnage, country, month sunk</span> c.&nbsp;The footnote refers to losses in December 1941 in the Far East, when Japan entered the war. How would you incorporate the information in the footnote into the imagined data frame? <span style="color: grey; font-style: italic;"><em>Answer</em>: Add a variable “location.”</span></li>
</ol></li>
<li><p>As you will see, with “data wrangling” it is easy to construct summary tables such as the one in <a href="#fig-shipping-losses" class="quarto-xref">Figure&nbsp;<span>1.5</span></a> from “raw data” as described in (4). But suppose you wanted to translate the information in the table into a tidy form with just four variables? What would these variables be? <span style="color: grey; font-style: italic;"><em>Answer</em>: month,country,number of ships, tons </span></p></li>
</ol>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-16-contents" aria-controls="callout-16" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 1.11 sheep-stand-drawer
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-16" class="callout-16-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The meta-data for <a href="#tbl-pine-hit-pants" class="quarto-xref">Table&nbsp;<span>1.2</span></a> (in Exercise 1.9) should include a description of each variable, its units, and what it stands for. Write such a description for the variables <code>crashes</code> and <code>resident_pop</code>. You can refer to <a href="#fig-bear-ride-pants1" class="quarto-xref">Figure&nbsp;<span>1.4</span></a> (in Exercise 1.1) for information.</p>
<p><em>Answer</em>:</p>
<div style="border-style: dotted; font-style: italic; margin-left: 1em;">
<ul>
<li><code>crashes</code> – the number of motor-vehicle accidents in one year which resulted in one or more fatalities. Units: number of accidents</li>
<li><code>resident_pop</code> – the population of the US in one year. Units: 1000s of people.</li>
</ul>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-17-contents" aria-controls="callout-17" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 1.12 eagle-spend-gloves
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-17" class="callout-17-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Glaucoma is a disease of the eye that is a leading cause of blindness worldwide. For those people with access to good eye health care, a diagnosis of glaucoma leads to treatment as well as monitoring of the possible progression of the disease. There are many forms of monitoring. One of them, the visual field examination, involves making measurements of light sensitivity at 54 locations arrayed across the retina. The data frame shown below (provided by the <code>womblR</code> R package) records the light sensitivity for one patient at each of the locations. Data from two visits – an initial visit marked 1 and a follow-up visit marked 2 which occurred 126 days after the initial visit – are contained in the data frame.</p>
<div class="cell" data-layout-align="FALSE">
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">location</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">day</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">visit</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">sensitivity</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">25</td>
</tr>
<tr class="even">
<td style="text-align: right;">1</td>
<td style="text-align: right;">126</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">23</td>
</tr>
<tr class="odd">
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">25</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">126</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">23</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">24</td>
</tr>
<tr class="even">
<td style="text-align: right;">3</td>
<td style="text-align: right;">126</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">24</td>
</tr>
<tr class="odd">
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">25</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">126</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">24</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">26</td>
</tr>
<tr class="even">
<td style="text-align: right;">5</td>
<td style="text-align: right;">126</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">17</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="text-align: right; padding: 0;"><sup></sup> ... and so on for 108 rows altogether.</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
</tfoot>

</table>


</div>
</div>
<ol type="a">
<li>What is the unit of observation? <span style="color: grey; font-style: italic;"><em>Answer</em>: a single location on a single visit</span></li>
<li>Suppose a third visit was made and the new data were included in the table.
<ul>
<li>How many columns would the revised table include? <span style="color: grey; font-style: italic;"><em>Answer</em>: The extended table will have the same four columns.</span></li>
<li>How many rows would the revised table include? <span style="color: grey; font-style: italic;"><em>Answer</em>: There are 54 rows for each visit. That’s why there are 108 rows in the original table. The revised table will have 54 x 3 = 162 rows. </span></li>
</ul></li>
<li>Note that <code>day</code> and <code>visit</code> have a very simple relationship. Construct a separate table that has all the information relating <code>day</code> to <code>visit</code>. The unit of observation should be “a visit”.</li>
</ol>
<p><em>Answer</em>:</p>
<div style="border-style: dotted; font-style: italic; margin-left: 1em;">
<p>It will be a very small table. The unit of observation is “a visit” and there are only two visits, so there will be only two rows.</p>
<div class="cell" data-layout-align="FALSE">
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">visit</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">day</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">126</td>
</tr>
</tbody>
</table>


</div>
</div>
</div>
<ol start="4" type="a">
<li><p>Each <code>location</code> is a fixed point on the eye’s retina that can be identified by (x, y) coordinates. Here is a map showing the position of each location. Notice that location 1 has position (4, 1) and location 2 has position (5, 1). Imagine a data frame that records the position of each <code>location</code>.</p>
<ul>
<li>How many columns would the data frame have and what would be sensible names for them? <span style="color: grey; font-style: italic;"><em>Answer</em>: <code>location</code>, <code>x</code>, and <code>y</code></span></li>
<li>How many rows would the data frame have? <span style="color: grey; font-style: italic;"><em>Answer</em>: There are 54 locations so there will be 54 rows in the data frame.</span></li>
<li>Write down the data table for positions 1, 2, 3, 4, 5, and 6.</li>
</ul></li>
</ol>
<div class="cell" data-layout-align="FALSE">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-FALSE">
<figure class="figure">
<p><img src="L01-Data-frames_files/figure-html/eagle-spend-gloves-3-1.png" class="img-fluid quarto-figure quarto-figure-FALSE figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p><em>Answer</em>:</p>
<div style="border-style: dotted; font-style: italic; margin-left: 1em;">
<div class="cell" data-layout-align="FALSE">
<div class="cell-output-display">
<table class="table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th">location</th>
<th data-quarto-table-cell-role="th">x</th>
<th data-quarto-table-cell-role="th">y</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>4</td>
<td>1</td>
</tr>
<tr class="even">
<td>2</td>
<td>5</td>
<td>1</td>
</tr>
<tr class="odd">
<td>3</td>
<td>6</td>
<td>1</td>
</tr>
<tr class="even">
<td>4</td>
<td>7</td>
<td>1</td>
</tr>
<tr class="odd">
<td>5</td>
<td>3</td>
<td>2</td>
</tr>
<tr class="even">
<td>6</td>
<td>4</td>
<td>2</td>
</tr>
</tbody><tfoot>
<tr class="odd">
<td style="padding: 0"><sup></sup> ... and so on for 54 rows altogether.</td>
<td></td>
<td></td>
</tr>
</tfoot>

</table>


</div>
</div>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-18-contents" aria-controls="callout-18" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 1.13 data-galton-table
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-18" class="callout-18-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Historians have access to the physical notebook in which Francis Galton originally recorded the data on heights shown in <a href="#tbl-galton-dataframe" class="quarto-xref">Table&nbsp;<span>1.1</span></a>. Galton’s data is given as tables: intended for human eyes. (Galton worked well before the invention of modern computing.)</p>
<p>Here is part of Galton’s notebook holding the height data table:</p>
<div class="cell" data-layout-align="FALSE">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-FALSE">
<figure class="figure">
<p><img src="www/galton-notebook-excerpt.png" class="img-fluid quarto-figure quarto-figure-FALSE figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>Describe the ways in which Galton’s data organization differs from that of a data frame.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-19-contents" aria-controls="callout-19" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 1.14 data-natal-unit
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-19" class="callout-19-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<!-- Q01-102-->
<p>The data frames <code>natality2014::Natality_2014_100K</code> and <code>mosaicData::Births78</code> relate to babies born in 2014 and 1978 respectively. They have utterly different <em>units of observation</em>.</p>
<ol type="a">
<li><p>What are the units of observation of each of these two data frames? (Hint: Look at the documentation for each of them using the <code>?</code> command described in <a href="#sec-codebook" class="quarto-xref"><span>Section 1.2</span></a>.)</p></li>
<li><p>What are the <em>levels</em> of the categorical variable <code>wday</code> in <code>Births78</code>? (Hint: Use <code>head()</code> or <code>View()</code>.)</p></li>
<li><p>One deficiency in the documentation of <code>Natality_2014_100K</code> is that the documentation for variable <code>dwgt_r</code> does not say what units (if any) the values are in. The values are numbers in the range 100 to 400. To judge from the documentation, what are the units of <code>dwgt_r</code>?</p></li>
</ol>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-20-contents" aria-controls="callout-20" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 1.15 Q01-103
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-20" class="callout-20-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<!--Q01-103-->
<p>In the text, we stated that the “unit of observation” of the dataframe shown in <a href="#tbl-galton-dataframe" class="quarto-xref">Table&nbsp;<span>1.1</span></a>, is a “individual, fully grown person.”</p>
<p>Suppose that a devil’s advocate claimed that this is incorrect, and that the unit of observation is really a <em>family</em>, not an individual. What can you point to in the data frame to argue the point?</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-21-contents" aria-controls="callout-21" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 1.16 Q01-105
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-21" class="callout-21-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<!-- Q01-105-->
<p>The text states that “<a href="#tbl-galton-dataframe" class="quarto-xref">Table&nbsp;<span>1.1</span></a> shows part of a data frame.” The nature of data frames is that there are two completely distinct ways that data frame might be extended to include more data. What are they?</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-22-contents" aria-controls="callout-22" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 1.17 Q01-106
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-22" class="callout-22-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The table below is from a so-called “population schedule” from the 1940 US Census. Column 1 indicates that the people listed live on N. Nevada Street. Columns 8 and 9 list the names of the individual people and their role in the household.</p>
<div class="cell" data-layout-align="FALSE">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-FALSE">
<figure class="figure">
<p><img src="www/1940-Colorado-Springs-excerpt.png" class="img-fluid quarto-figure quarto-figure-FALSE figure-img" style="width:80.0%"></p>
</figure>
</div>
</div>
</div>
<p>In 1940, principles of data organization were primitive. Using modern principles, raw data such as this would be arranged so that the <em>order</em> of the rows does not matter.</p>
<p>Explain why, in the 1940 table, the order of rows makes a big difference. For example, consider what would be changed about the data if, say, row 42 were moved to be between rows 47 and 48.</p>
<p><span style="color: grey; font-style: italic;"><em>Answer</em>: If row 42 were moved down by six rows, Louisa W. Service would become Louisa W. Platt, Douglas H Platt would become a bigamist with two wives, and William C Service would become a single parent! That’s inconsistent with the actual facts.</span></p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-23-contents" aria-controls="callout-23" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 1.18 Q01-107
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-23" class="callout-23-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<!-- Q01-107 -->
<p>Using your web browser, open this link in a new tab: <a href="https://www.mosaic-web.org/go/datasets/engines.csv" class="uri">https://www.mosaic-web.org/go/datasets/engines.csv</a>.</p>
<p>Depending on how your browser is set up, you will either be directed to a web page showing a data frame about engines <strong>or</strong> the browser will download a file named “engines.csv” onto your computer.</p>
<p>The <code>.csv</code> suffix on the file name indicates that the file stored at the address <a href="https://www.mosaic-web.org/go/datasets/engines.csv" class="uri">https://www.mosaic-web.org/go/datasets/engines.csv</a> is in a format called “comma separated values.” The CSV format is a common way to store spreadsheet files.</p>
<p>In these <em>Lessons</em> most data frames will be accessed in a single step, by name. However, in professional work, data is stored in computer files or on the interweb. For such data, two steps are needed to access the data from within R.</p>
<p>Step 1. Read the file into R, translate the contents into the native R format for data frames, and store the data frame under a name. For a CSV file, an appropriate R function to read and translate the file is <code>readr::read_csv()</code>. As an argument to the function, give the address of the file, making sure to enclose the address in quotation marks: <code>"https://www.mosaic-web.org/go/datasets/engines.csv"</code>. This will cause <code>readr::read_csv()</code> to access the web address, then copy and translate the contents into an R format format for data frames. Use the <em>storage arrow</em> <code>&lt;-</code> to store the data frame under the name <code>Engines</code>.</p>
<p>Step 2. Use the storage name, in this example <code>Engines</code>, to access the data frame from within R.</p>
<p>Your task: Read in the “engines.csv” file to R as a data frame, storing it as <code>Engines</code>. Then use <code>nrow()</code> to calculate the number of rows in the data frame. In addition, use <code>names</code> to see the variable names.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-24-contents" aria-controls="callout-24" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 1.19 Q01-108
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-24" class="callout-24-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<!-- Q01-108 -->
<p>Many organizations, such as government agencies, provide access to data collected during their normal operations. For instance, New York City has an “open data” site that, among many other data frames, shows parking violations in the city over the last several years.</p>
<p>Using your web browser, go to the front page for the parking violation data: <a href="https://data.cityofnewyork.us/City-Government/Open-Parking-and-Camera-Violations/nc67-uf89" class="uri">https://data.cityofnewyork.us/City-Government/Open-Parking-and-Camera-Violations/nc67-uf89</a>. The front page provides several resources about the data, as well as a small preview of a handful of rows of the data frame. (Don’t try to read the data into R; it’s too big to be easily handled on a laptop computer.) Looking at the front page, answer these questions:</p>
<ol type="1">
<li><p>How many rows are in the data frame? <span style="color: grey; font-style: italic;"><em>Answer</em>: This depends on the date you look at the data, but as of December 2023, there were over 107 million rows!</span></p></li>
<li><p>The third column is labelled “License Type.” Only two types—<code>PAS</code> and <code>COM</code>—are shown in the first page of the data preview. Scroll down through the data preview until you have found three other license types. Which ones did you find? <span style="color: grey; font-style: italic;"><em>Answer</em>: OMS, OMR, OMT appear within the first few pages.</span></p></li>
<li><p>According to the front page, the unit of observation is an “Open Parking and Camera Violations [sic] Issued.” (Actually, the unit is a <em>single</em> violation.) The front page doesn’t use the term “unit of observation.” What term does it use instead? <span style="color: grey; font-style: italic;"><em>Answer</em>: “Each row is a …”</span></p></li>
</ol>
</div>
</div>
</div>
<div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-25-contents" aria-controls="callout-25" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 1.20 Q01-104
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-25" class="callout-25-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The unit of observation in the <code>mosaicData::KidsFeet</code> data frame is a 3rd- or 4th-grade student in the elementary school attended by a statistician’s daughter. You can see the first few rows by giving the R command</p>
<div class="cell" data-layout-align="FALSE" data-digits="2">
<div class="cell-output-display">
<div style="font-family: Monospace;">
<table class="lightable-minimal table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">name</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">birthmonth</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">birthyear</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">length</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">width</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">sex</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">biggerfoot</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">domhand</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">David</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">88</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">8.4</td>
<td style="text-align: left;">B</td>
<td style="text-align: left;">L</td>
<td style="text-align: left;">R</td>
</tr>
<tr class="even">
<td style="text-align: left;">Lars</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">87</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">8.8</td>
<td style="text-align: left;">B</td>
<td style="text-align: left;">L</td>
<td style="text-align: left;">L</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zach</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">87</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">9.7</td>
<td style="text-align: left;">B</td>
<td style="text-align: left;">R</td>
<td style="text-align: left;">R</td>
</tr>
<tr class="even">
<td style="text-align: left;">Josh</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">88</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">9.8</td>
<td style="text-align: left;">B</td>
<td style="text-align: left;">L</td>
<td style="text-align: left;">R</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Lang</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">88</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">8.9</td>
<td style="text-align: left;">B</td>
<td style="text-align: left;">L</td>
<td style="text-align: left;">R</td>
</tr>
<tr class="even">
<td style="text-align: left;">Scotty</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">88</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">9.7</td>
<td style="text-align: left;">B</td>
<td style="text-align: left;">R</td>
<td style="text-align: left;">R</td>
</tr>
</tbody>
</table>
</div>
</div>
<ol type="1">
<li><p>For each variable, say whether “categorical” or “numerical” gives the better description of the variable’s type.</p></li>
<li><p>The <code>birthmonth</code> and <code>birthyear</code> variables are written with numerals, but this is due to deficiencies in the software used to record the data in the 1990s. Describe at least one of the ways in which <code>birthmonth</code> does not behave like a number. (Hint: Is 12/1987 close or far from 01/1988?)</p></li>
</ol>
</div>
</div>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-26-contents" aria-controls="callout-26" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Exercise 1.21 kitten-drink-sofa
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-26" class="callout-26-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>The data table below records activity at a neighborhood car repair shop.</p>
<div class="cell" data-layout-align="FALSE">
<div class="cell-output-display">
<div style="font-family: Monospace;">
<table class="lightable-minimal table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">mechanic</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">product</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">price</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">date</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Anne</td>
<td style="text-align: left;">starter</td>
<td style="text-align: right;">170.00</td>
<td style="text-align: left;">2019-01-12</td>
</tr>
<tr class="even">
<td style="text-align: left;">Beatrice</td>
<td style="text-align: left;">shock absorber</td>
<td style="text-align: right;">78.42</td>
<td style="text-align: left;">2019-01-12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Anne</td>
<td style="text-align: left;">alternator</td>
<td style="text-align: right;">385.95</td>
<td style="text-align: left;">2019-01-12</td>
</tr>
<tr class="even">
<td style="text-align: left;">Clarisse</td>
<td style="text-align: left;">brake shoe</td>
<td style="text-align: right;">39.50</td>
<td style="text-align: left;">2019-01-12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Clarisse</td>
<td style="text-align: left;">brake shoe</td>
<td style="text-align: right;">39.50</td>
<td style="text-align: left;">2019-01-12</td>
</tr>
<tr class="even">
<td style="text-align: left;">Beatrice</td>
<td style="text-align: left;">radiator hose</td>
<td style="text-align: right;">17.90</td>
<td style="text-align: left;">2019-02-12</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The codebook for a data table should describe what is the unit of observation. For the purpose of this exercise, your job is to comment on each of the following possibilities and say why or why not it is plausibly the unit of observation.</p>
<ol type="a">
<li><p>a day. <span style="color: grey; font-style: italic;"><em>Answer</em>: There must be more to it than that, since the same date may be repeated with different values for the other variables.</span><br>
</p></li>
<li><p>a mechanic. <span style="color: grey; font-style: italic;"><em>Answer</em>: No.&nbsp;The same mechanic appears multiple times, so the unit of observation is not simply a mechanic.</span></p></li>
<li><p>a car part used in a repair. <span style="color: grey; font-style: italic;"><em>Answer</em>: Could be, for instance if every time a mechanic installs a part a new entry is added to the table describing the part, its price, the date, and the mechanic doing the work.</span></p></li>
</ol>
</div>
</div>
</div>
<!--


::: {.callout-note collapse="true"}
## Exercise 1.22     pine-show-piano-F-5 



DRAFT, talk about date-times and why the CDC data uses `month` and `day of week`.

:::





::: {.callout-note collapse="true"}
## Exercise 1.23     data-improper 




This *table* of values is *not* a proper data frame. Why not?

Have variables with mixed types, and shift units of observations from countries to individuals.
:::



::: {.callout-note collapse="true"}
## Exercise 1.24     data-open-codebook 



Direct the reader to one of the open data sites, e.g. <https://data.cityofnewyork.us/City-Government/Open-Parking-and-Camera-Violations/nc67-uf89> Point out that the web site is a combination of documentation, a "table preview", and a way to access a spreadsheet CSV file containing the data. 

A small part of this data is provided as `LSTbook::NYC_parking`. 
:::

-->


</div></div></section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./index.html" class="pagination-link  aria-label=" preface"="">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Preface</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./L02-Pointplots.html" class="pagination-link" aria-label="<span class='chapter-number'>2</span>&nbsp; <span class='chapter-title'>Data graphics</span>">
        <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data graphics</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/dtkaplan/Lessons-in-statistical-thinking/blob/main/L01-Data-frames.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li></ul></div></div></div></footer></body></html>