<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.549">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Lessons in Statistical Thinking - 11&nbsp; Model functions</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./L12-Adjustment.html" rel="next">
<link href="./L10-Model-patterns.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./L08-Statistical-thinking.html">Describing relationships</a></li><li class="breadcrumb-item"><a href="./L11-Regression.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Model functions</span></a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Lessons in Statistical Thinking</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/dtkaplan/Lessons-in-statistical-thinking/" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <span class="sidebar-item-text sidebar-link text-start">
 <span class="menu-text"> </span></span>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Handling data</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L01-Data-frames.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Data frames</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L02-Pointplots.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data graphics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L03-Variation-and-distribution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Variation and density, graphically</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L04-Model-annotations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Annotating point plots with a model</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L05-Wrangling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Data wrangling</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L06-Computing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Computing with functions and arguments</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L07-Databases.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Databases</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">Describing relationships</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L08-Statistical-thinking.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Statistical thinking &amp; variation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L09-Accounting-for-variation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Accounting for variation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L10-Model-patterns.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Model patterns</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L11-Regression.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Model functions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L12-Adjustment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Adjustment</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">Randomness and noise</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L13-Signal-and-noise.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Signal and noise</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L14-Simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Simulation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L15-Noise-patterns.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Noise models</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L16-Estimation-and-likelihood.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Estimation and likelihood</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L17-R-squared.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">R-squared and covariates</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L18-Prediction.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Predictions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L19-Sampling-variation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Sampling and sampling variation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L20-Confidence-intervals.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Confidence intervals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L21-Measuring-and-accumulating-risk.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Measuring and accumulating risk</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
 <span class="menu-text">Causal modeling</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L22-Effect-size.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Effect size</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L23-DAGs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Directed acyclic graphs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L24-Causality-and-DAGS.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Causal influence and DAGs</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L25-Confounding.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Confounding</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L26-Experiment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Experiment and random assignment</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true">
 <span class="menu-text">Hypothetical Thinking</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L27-Hypothetical-thinking.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Hypothetical thinking</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L28-Bayes.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Competing hypotheses with Bayesian reasoning</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./L29-NHT.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Hypothesis testing</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Glossary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Glossary</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-math-function-basics" id="toc-sec-math-function-basics" class="nav-link active" data-scroll-target="#sec-math-function-basics">Basics of mathematical functions</a></li>
  <li><a href="#statistical-models" id="toc-statistical-models" class="nav-link" data-scroll-target="#statistical-models">Statistical models</a></li>
  <li><a href="#training-a-model" id="toc-training-a-model" class="nav-link" data-scroll-target="#training-a-model">Training a model</a></li>
  <li><a href="#model-functions-with-multiple-explanatory-variables" id="toc-model-functions-with-multiple-explanatory-variables" class="nav-link" data-scroll-target="#model-functions-with-multiple-explanatory-variables">Model functions with multiple explanatory variables</a></li>
  <li><a href="#case-study-get-out-the-vote" id="toc-case-study-get-out-the-vote" class="nav-link" data-scroll-target="#case-study-get-out-the-vote">Case study: Get out the vote!</a></li>
  <li><a href="#tradition-and-correlation" id="toc-tradition-and-correlation" class="nav-link" data-scroll-target="#tradition-and-correlation">Tradition and “correlation”</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/dtkaplan/Lessons-in-statistical-thinking/blob/main/L11-Regression.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./L08-Statistical-thinking.html">Describing relationships</a></li><li class="breadcrumb-item"><a href="./L11-Regression.html"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Model functions</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-regression" class="quarto-section-identifier"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Model functions</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>From the start of these Lessons, we have talked about revealing patterns in data, particularly those that describe relationships among variables. Graphics show patterns in a way that is particularly attuned to human cognition, and we have leaned on them heavily. In this Lesson, we turn to another form of description of relationships between variables: simple mathematical functions.</p>
<section id="sec-math-function-basics" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="sec-math-function-basics">Basics of mathematical functions</h2>
<p>We will need only the most basic ideas of mathematics to enable our work with functions. There won’t be any algebra required.</p>
<ol type="1">
<li><p>In mathematics, a function is a relationship between one or more inputs and an output. In our use of functions for statistical thinking, the output corresponds to the response variable, the inputs to the explanatory variables.</p></li>
<li><p>In mathematical notation, functions are conventionally written idiomatically using single-letter names. For instance, letters from the end of the alphabet—<span class="math inline">\(x\)</span>, <span class="math inline">\(y\)</span>, <span class="math inline">\(t\)</span>, and <span class="math inline">\(z\)</span>—are names for function inputs. The convention uses letters from the start of the alphabet as stand-ins for numerical values; these are called <strong>parameters</strong> or, equivalently, <strong>coefficients</strong>. These conventions are almost 400 years old and are associated with Isaac Newton (1643-1727).</p>
<p>Not quite 300 years ago, a new mathematical idea, the function, was introduced by Leonhard Euler (1707-1783). Since the start and end of the alphabet had been reserved for names of variables and parameters, a convention emerged to use the letters <span class="math inline">\(f\)</span> and <span class="math inline">\(g\)</span> for function names.</p></li>
<li><p>To say, “Use function <span class="math inline">\(f\)</span> to transform the inputs <span class="math inline">\(x\)</span> and <span class="math inline">\(t\)</span> to an output value,” the notation is <span class="math inline">\(f(x, t)\)</span>. To emphasize: Remember that <span class="math inline">\(f(x, t)\)</span> stands for the <strong>output</strong> of the function. Statistics often uses the one-letter name style, but when the letters stand for things in the real world, it can be preferable to use names that remind us what they stand for: <code>age</code>, <code>time_of_day</code>, <code>mother</code>, <code>wrist</code>, <code>prices</code>, and such.</p></li>
<li><p>Mathematical functions are idealizations. Importantly, they differ from much of everyday experience. Every mathematical function may have only one <em>output value</em> for any given <em>input value</em>. We say that mathematical functions are “<strong>single valued</strong>. For instance, the mathematical value <span class="math inline">\(f(x=3, t=10)\)</span> will be the same every time it is calculated. In everyday life, a quantity like <code>cooking_time(temperature=300)</code>might vary depending on other factors (like <code>altitude</code>) or even randomly.</p>
<p>When functions are graphed, the single-valued property is shown using a thin line for the function value, as it depends on the inputs. (See <a href="#fig-single-valued" class="quarto-xref">Figure&nbsp;<span>11.1</span></a>.)</p></li>
</ol>

<div class="no-row-height column-margin column-container"><div id="fig-single-valued" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-single-valued-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div>

</div>
<div class="cell quarto-layout-panel" data-layout-ncol="1">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="L11-Regression_files/figure-html/unnamed-chunk-2-1.png" class="lightbox" data-glightbox="description: .lightbox-desc-1" data-gallery="quarto-lightbox-gallery-1" title="Straight-line function"><img src="L11-Regression_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid figure-img" width="672"></a></p>
<figcaption>Straight-line function</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="L11-Regression_files/figure-html/unnamed-chunk-2-2.png" class="lightbox" data-glightbox="description: .lightbox-desc-2" data-gallery="quarto-lightbox-gallery-2" title="Sigmoidal function"><img src="L11-Regression_files/figure-html/unnamed-chunk-2-2.png" class="img-fluid figure-img" width="672"></a></p>
<figcaption>Sigmoidal function</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 100.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="L11-Regression_files/figure-html/unnamed-chunk-2-3.png" class="lightbox" data-glightbox="description: .lightbox-desc-3" data-gallery="quarto-lightbox-gallery-3" title="Discrete-input function"><img src="L11-Regression_files/figure-html/unnamed-chunk-2-3.png" class="img-fluid figure-img" width="672"></a></p>
<figcaption>Discrete-input function</figcaption>
</figure>
</div>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-single-valued-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11.1: Three examples of single-valued functions.
</figcaption>
</figure>
</div></div><ol start="5" type="1">
<li>In contrast to the large variety encountered in mathematics courses, we will need only the three function types shown in <a href="#fig-single-valued" class="quarto-xref">Figure&nbsp;<span>11.1</span></a>:
<ol type="a">
<li>Straight-line</li>
<li>Sigmoid curve, resembling a highly-slanted letter <em>S</em>.</li>
<li>Discrete-input, where the input is a categorical level. The function values, one for each level of the categorical input, are drawn as short horizontal strokes.</li>
</ol></li>
<li>A <strong>formula</strong> is an arithmetic expression written in terms of input names and coefficient names, for example, <span class="math inline">\(a x + b\)</span>. We write <span class="math inline">\(f(x) \equiv a x + b\)</span> to say that function <span class="math inline">\(f\)</span> is defined by the formula <span class="math inline">\(a x + b\)</span>. All three function types in (5) use two coefficients, <span class="math inline">\(a\)</span> and <span class="math inline">\(b\)</span>. The sigmoid function uses an S-shaped translation between <span class="math inline">\(ax + b\)</span> and the function output value.</li>
</ol>
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 21%">
<col style="width: 29%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>Function type</th>
<th>Algebraic</th>
<th>Math names</th>
<th>Statistics names</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Straight-line</td>
<td><span class="math inline">\(f(x) \equiv a x + b\)</span></td>
<td><span class="math inline">\(a\)</span> is “slope”</td>
<td><span class="math inline">\(a\)</span> is coefficient on <span class="math inline">\(x\)</span></td>
</tr>
<tr class="even">
<td>.</td>
<td>.</td>
<td><span class="math inline">\(b\)</span> is “intercept”</td>
<td><span class="math inline">\(b\)</span> is “intercept”</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Sigmoid</td>
<td><span class="math inline">\(f(x) \equiv S(a x + b)\)</span></td>
<td><span class="math inline">\(a\)</span> is “steepness”</td>
<td><span class="math inline">\(a\)</span> is coefficient on <span class="math inline">\(x\)</span></td>
</tr>
<tr class="odd">
<td>.</td>
<td>.</td>
<td><span class="math inline">\(b\)</span> is “center”</td>
<td><span class="math inline">\(b\)</span> is “intercept”</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Discrete-input</td>
<td><span class="math inline">\(f(x) \equiv b + \left\{\begin{array}{ll}0\ \text{when}\ x = F\\a\ \text{when}\ x=M\end{array}\right.\)</span></td>
<td><span class="math inline">\(b\)</span> is intercept</td>
<td><span class="math inline">\(b\)</span> is “intercept”</td>
</tr>
<tr class="even">
<td>.</td>
<td>.</td>
<td>.</td>
<td><span class="math inline">\(a\)</span> is “sexM coefficient”</td>
</tr>
</tbody>
</table>
<p>In all three cases, the <span class="math inline">\(a\)</span> coefficient quantifies how the function output changes in value as the input <span class="math inline">\(x\)</span> changes. For the straight-line function, <span class="math inline">\(a\)</span> is the slope. Similarly, <span class="math inline">\(a\)</span> is the steepness halfway up the curve for the sigmoid function. And for the discrete-input function, <span class="math inline">\(a\)</span> is the amount to add to the output when the input <span class="math inline">\(x\)</span> equals the particular categorical level (M in the above example).</p>
</section>
<section id="statistical-models" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="statistical-models">Statistical models</h2>
<p>Many mathematical functions are used in statistics, but to quantify a relationship among variables rooted in data, statistical thinkers use models that resemble a mathematical function but are <strong>bands</strong> or <strong>intervals</strong> rather than the thin marks of single-valued function graphs. <a href="#fig-some-model-annotations" class="quarto-xref">Figure&nbsp;<span>11.2</span></a> shows three such statistical models, each of which corresponds to one of the mathematical functions in <a href="#fig-single-valued" class="quarto-xref">Figure&nbsp;<span>11.1</span></a>.</p>
<div class="cell page-columns page-full">
<div id="fig-some-model-annotations" class="cell quarto-figure quarto-figure-center quarto-float anchored page-columns page-full">
<figure class="quarto-float quarto-float-fig figure page-columns page-full">
<div aria-describedby="fig-some-model-annotations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca" class="page-columns page-full">

<div class="no-row-height column-margin column-container"><div class="cell-output-display">
<div id="fig-some-model-annotations-1" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-some-model-annotations-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="L11-Regression_files/figure-html/fig-some-model-annotations-1.png" class="lightbox" data-glightbox="description: .lightbox-desc-4" data-gallery="fig-some-model-annotations"><img src="L11-Regression_files/figure-html/fig-some-model-annotations-1.png" class="img-fluid figure-img" data-ref-parent="fig-some-model-annotations" width="672"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-some-model-annotations-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) Sloping band
</figcaption>
</figure>
</div>
</div><div class="cell-output-display">
<div id="fig-some-model-annotations-2" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-some-model-annotations-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="L11-Regression_files/figure-html/fig-some-model-annotations-2.png" class="lightbox" data-glightbox="description: .lightbox-desc-5" data-gallery="fig-some-model-annotations"><img src="L11-Regression_files/figure-html/fig-some-model-annotations-2.png" class="img-fluid figure-img" data-ref-parent="fig-some-model-annotations" width="672"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-some-model-annotations-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) Sigmoid band
</figcaption>
</figure>
</div>
</div><div class="cell-output-display">
<div id="fig-some-model-annotations-3" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-some-model-annotations-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="L11-Regression_files/figure-html/fig-some-model-annotations-3.png" class="lightbox" data-glightbox="description: .lightbox-desc-6" data-gallery="fig-some-model-annotations"><img src="L11-Regression_files/figure-html/fig-some-model-annotations-3.png" class="img-fluid figure-img" data-ref-parent="fig-some-model-annotations" width="672"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-some-model-annotations-3-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(c) Groupwise intervals
</figcaption>
</figure>
</div>
</div></div>

</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-some-model-annotations-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11.2: Statistical models constructed from the <code>Galton</code> data frame.
</figcaption>
</figure>
</div>
</div>
<p>Quantifying uncertainty is a significant focus of statistics. The bands or intervals—the vertical extent of the model annotation—are an essential part of a statistical model. In contrast, single-valued mathematical functions come from an era that didn’t treat uncertainty as a mathematical topic.</p>
<p>To draw a model annotation, the computer first finds the single-valued mathematical function that passes through the band or interval at the mid-way vertical point. We will identify such single-valued functions as “<strong>model functions</strong>.” Model functions can be written as <strong>model formulas</strong>, as described in <a href="#sec-math-function-basics" class="quarto-xref"><span>Section 11.1</span></a>.</p>
<p>Another critical piece is needed to draw a model annotation: the vertical spread of the statistical annotation that captures the uncertainty. This is an <em>essential</em> component of a statistical model. Before dealing with uncertainty, we will need to develop concepts and tools about randomness and noise as presented in Lessons <a href="L13-Signal-and-noise.html" class="quarto-xref"><span>13</span></a> through <a href="L19-Sampling-variation.html" class="quarto-xref"><span>19</span></a>.</p>
<p>For now, however, we will focus on the model function, particularly on the interpretation of the coefficients. We won’t need formulas for this. Instead, focus your attention on two kinds of coefficients:</p>
<ul>
<li><p>the intercept, which we wrote as <span class="math inline">\(b\)</span> when discussing mathematical functions. In statistical reports, it is usually written <code>(Intercept)</code>.</p></li>
<li><p>the other coefficient, which we named <code>a</code> to represent the slope/steepness/change, always measures how the model function output changes for different values of the explanatory variable. If <span class="math inline">\(x\)</span> is the name of a <em>quantitative</em> explanatory variable, the coefficient is called the “<span class="math inline">\(x\)</span>-coefficient. But for a categorical explanatory variable, the coefficient refers to <em>both</em> the name of the explanatoryry variable <em>and</em> the particular level to which it applies. For example, in <a href="#fig-some-model-annotations" class="quarto-xref">Figure&nbsp;<span>11.2</span></a>(c), the explanatory variable is <code>sex</code> and the level is M, so the coefficient is named <code>sexM</code>.</p></li>
</ul>
</section>
<section id="training-a-model" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="training-a-model">Training a model</h2>
<div class="page-columns page-full"><p>The model annotation in an annotated point plot is arranged to show the model function and uncertainty simultaneously. To construct the model in the annotation, <code>point_plot()</code> uses another function: <code>model_train()</code>. </p><div class="no-row-height column-margin column-container"><span class="margin-aside">“Train” is meant in the sense of “training a pet” or “vocational training.” <code>model_train()</code> has nothing to do with miniature-scale transportation layouts found in hobbyists’ basements.</span></div></div>
<p>Now that we have introduced model functions and coefficients, we can explain what <code>model_train()</code> does:</p>
<blockquote class="blockquote">
<p><code>model_train()</code> finds numerical values for the coefficients that cause the model function to align as closely as possible to the data. As part of this process, <code>model_train()</code> also calculates information about the uncertainty, but we put that off until later.)</p>
</blockquote>
<p>Use <code>model_train()</code> in the same way as <code>point_plot()</code>. A data frame is the input. The only required argument is a tilde expression specifying the names of the response variable and the explanatory variables, just as in <code>point_plot()</code>.</p>
<p>As you know, the output from <code>point_plot()</code> is a <em>graphic</em>. Similarly, the output from wrangling functions is a <em>data frame</em>. The output of <code>model_train()</code> is not a graphic (like <code>point_plot()</code>) or a data frame (like the wrangling functions). Instead, it is a new kind of thing that we call a “<strong>model object</strong>.”</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>Galton <span class="sc">|&gt;</span> <span class="fu">model_train</span>(height <span class="sc">~</span> mother)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
stats::lm(formula = tilde, data = data)

Coefficients:
(Intercept)       mother  
    46.6908       0.3132  </code></pre>
</div>
</div>
<p>Recall that <em>printing</em> is default operation to do with the object produced at the end of a pipeline. Printing a data frame or a graphic displays more-or-less the entire object. But for model objects, printing gives only a glimpse of the object. This is because there are multiple perspectives to take on model objects, for instance, the model function or the uncertainty.</p>
<p>Choose the perspective you want by piping the model output into another function, two of which we describe here:</p>
<p><code>model_eval()</code> looks at the model object from the perspective of a model function. The arguments to <code>model_eval()</code> are values for the explanatory variables. For instance, consider the height of the child of a mother who is five feet five inches (65 inches):</p>
<div class="cell" data-digits="1">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>Galton <span class="sc">|&gt;</span> <span class="fu">model_train</span>(height <span class="sc">~</span> mother) <span class="sc">|&gt;</span> <span class="fu">model_eval</span>(<span class="at">mother =</span> <span class="dv">65</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div style="font-family: Monospace;">
<table class="lightable-minimal table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">mother</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">.lwr</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">.output</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">.upr</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">60</td>
<td style="text-align: right;">60</td>
<td style="text-align: right;">70</td>
<td style="text-align: right;">70</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The output of <code>model_eval()</code> is a data frame. The <code>mother</code> column repeats the input value given to <code>model_eval()</code>. <code>.output</code> gives the model output: a child’s height of 67 inches. There are two other columns: <code>.lwr</code> and <code>.upr</code>. These relate to the uncertainty in the model output. We will discuss these in due time. For the present, we simply note that, according to the model, the child of a 65-inch tall mother is likely to be between 60 and 74 inches</p>
<p><code>conf_interval()</code> provides a different perspective on the model object: the <em>coefficients</em> of the model function.</p>
<div class="cell" data-digits="1">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>Galton <span class="sc">|&gt;</span> <span class="fu">model_train</span>(height <span class="sc">~</span> mother) <span class="sc">|&gt;</span> <span class="fu">conf_interval</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div style="font-family: Monospace;">
<table class="lightable-minimal table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">.lwr</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">.coef</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">.upr</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">40.0</td>
<td style="text-align: right;">50.0</td>
<td style="text-align: right;">50.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">mother</td>
<td style="text-align: right;">0.2</td>
<td style="text-align: right;">0.3</td>
<td style="text-align: right;">0.4</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The form of the output is, as you might guess, a data frame. The <code>term</code> value identifies which coefficient the row refers to; the <code>.coef</code> column gives the numerical value of the coefficient. Once again, there are two additional columns, <code>.lwr</code> and <code>.upr</code>. These describe the uncertainty in the coefficient. Again, we will get to this in due time.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Regression models versus classifiers
</div>
</div>
<div class="callout-body-container callout-body">
<p>There are two major kinds of statistical models: <strong>regression models</strong> and <strong>classifiers</strong>. In a regression model, the response variable is always a <em>quantitative</em> variable. For a classifier, on the other hand, the response variable is <em>categorical</em>.</p>
<p>These Lessons involve only <strong>regression</strong> models. The reason: This is an introduction, and regression models are easier to express and interpret. Classifiers involve multiple model functions; the bookkeeping involved can be tedious. (We’ll return to classifiers in <a href="L21-Measuring-and-accumulating-risk.html" class="quarto-xref"><span>21</span></a>.)</p>
<p>However, one kind of classifier is within our scope because it is also a regression model. How can that happen? When a categorical variable has only two levels (say, dead and alive), we can translate it into zero-one format. A two-level categorical variable is also a numerical variable but with the numerical levels zero and one.</p>
<p>When the response variable is zero-one, we can use regression techniques. Often, it is advisable to use a custom-built technique called <strong>logistic regression</strong>. <code>model_train()</code> knows when to use logistic regression. The sigmoidal shape is a good indication that logistic regression is in use. (See, e.g. <a href="#fig-some-model-annotations" class="quarto-xref">Figure&nbsp;<span>11.2</span></a>(b))</p>
<p>“Regression” is a strange name for a statistical/mathematical technique. It comes from a misunderstanding in the early days of statistics, which remains remarkably prevalent today. See Additional Topic Enrichment topic 11.1 Regression to the mean.</p>
</div>
</div>
</div></div></section>
<section id="model-functions-with-multiple-explanatory-variables" class="level2">
<h2 class="anchored" data-anchor-id="model-functions-with-multiple-explanatory-variables">Model functions with multiple explanatory variables</h2>
<p>The ideas of model functions and coefficients apply to models with multiple explanatory variables. To illustrate, let’s return to the <code>Galton</code> data and use the heights of the <code>mother</code> and <code>father</code> and the child’s <code>sex</code> to account for the child’s height.</p>
<p>The printed version of the model doesn’t give any detail …</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>Galton <span class="sc">|&gt;</span> </span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model_train</span>(height <span class="sc">~</span> mother <span class="sc">+</span> father <span class="sc">+</span> sex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
stats::lm(formula = tilde, data = data)

Coefficients:
(Intercept)       mother       father         sexM  
    15.3448       0.3215       0.4060       5.2260  </code></pre>
</div>
</div>
<p>… but the coefficients tell us about the relationships:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>Galton <span class="sc">|&gt;</span> </span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model_train</span>(height <span class="sc">~</span> mother <span class="sc">+</span> father <span class="sc">+</span> sex) <span class="sc">|&gt;</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">conf_interval</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div style="font-family: Monospace;">
<table class="lightable-minimal table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">.lwr</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">.coef</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">.upr</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">9.9535161</td>
<td style="text-align: right;">15.3447600</td>
<td style="text-align: right;">20.7360040</td>
</tr>
<tr class="even">
<td style="text-align: left;">mother</td>
<td style="text-align: right;">0.2601008</td>
<td style="text-align: right;">0.3214951</td>
<td style="text-align: right;">0.3828894</td>
</tr>
<tr class="odd">
<td style="text-align: left;">father</td>
<td style="text-align: right;">0.3486558</td>
<td style="text-align: right;">0.4059780</td>
<td style="text-align: right;">0.4633002</td>
</tr>
<tr class="even">
<td style="text-align: left;">sexM</td>
<td style="text-align: right;">4.9433183</td>
<td style="text-align: right;">5.2259513</td>
<td style="text-align: right;">5.5085843</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>There are four coefficients in this model. As always, there is the intercept, which we wrote <span class="math inline">\(b\)</span> in <a href="#sec-math-function-basics" class="quarto-xref"><span>Section 11.1</span></a>. But instead of one <span class="math inline">\(a\)</span> coefficient, each explanatory variable has a separate coefficient.</p>
<p>The intercept, 15.3 inches, gives a kind of baseline: what the child’s height would be before taking into account <code>mother</code>, <code>father</code> and <code>sex</code>. Of course, this is utterly unrealistic because there must always be a mother and father.</p>
<p>Like the <span class="math inline">\(a\)</span> coefficient in <a href="#sec-math-function-basics" class="quarto-xref"><span>Section 11.1</span></a>, the coefficients for the explanatory variables express the change in model output per change in value of the explanatory variable. The mother coefficient, 0.32, expresses how much the model output will change for each inch of the mother’s height. So, for a mother who is 65 inches tall, add <span class="math inline">\(0.32 \times 65 = 20.8\)</span> inches to the model output. Similarly, the <code>father</code> coefficient expresses the change in model output for each inch of the father’s height. For a 68-inch father, that adds another <span class="math inline">\(0.41 \times 68 = 27.9\)</span> inches to the model output.</p>
<p>The <code>sexM</code> coefficient gives the increase in model output when the child has level M for <code>sex</code>. So add another 5.23 inches for male children.</p>
<p>There is no <code>sexF</code> coefficient, but this is only a matter of accounting. R chooses one level of a categorical variable to use as a baseline. Usually, the choice is alphabetical: “F” comes before “M,” so females are the baseline.</p>
</div></section>
<section id="case-study-get-out-the-vote" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="case-study-get-out-the-vote">Case study: Get out the vote!</h2>
<p>There is perennial concern with voter participation in many countries: only a fraction of potential voters do so. Many civic organizations seek to increase voter turnout. Political campaigns spend large amounts of money on advertising and knock-on-the-door efforts in competitive districts. (Of course, they focus on neighborhoods where the campaign expects voters to be sympathetic to them.) However, civic organizations don’t have the fund-raising capability of campaigns. Is there an inexpensive way for these organizations to get out the vote?</p>
<div class="page-columns page-full"><p>Consider an experiment in which get-out-the-vote post-cards with messages of possibly different persuasive force were sent randomly to registered voters before the 2006 mid-term election.  The message on each post-card was one of the following:</p><div class="no-row-height column-margin column-container"><span class="margin-aside">See Alan S. Gerber, Donald P. Green, and Christopher W. Larimer (2008) “Social pressure and voter turnout: Evidence from a large-scale field experiment.” American Political Science Review, vol.&nbsp;102, no. 1, pp.&nbsp;33–48</span></div></div>
<ul>
<li><p>The “Neighbors” message listed the voter’s neighbors and whether they had voted in the previous primary elections. The card promised to send out the same information after the 2006 primary so that “you and your neighbors will all know who voted and who did not.”</p></li>
<li><p>The “Civic Duty” message was, “Remember to vote. DO YOUR CIVIC DUTY—VOTE!”</p></li>
<li><p>The “Hawthorne” message simply told the voter that “YOU ARE BEING STUDIED!” as part of research on why people do or do not vote. [The [name comes from studies](https://en.wikipedia.org/wiki/Hawthorne_effect] conducted at the “Hawthorne Works” in Illinois in 1924 and 1927. Small changes in working conditions inevitably <em>increased</em> productivity for a while, even when the change undid a previous one.]{.aside}</p></li>
<li><p>A “control group” of potential voters, picked at random, received no post-card.</p></li>
</ul>
<p>The voters’ response—whether they voted in the election—was gleaned from public records. The data involving 305,866 voters is in the <code>Go_vote</code> data frame. Three of the variables are of clear relevance: the type of get-out-the-vote message (in <code>messages</code>), whether the voter voted in the upcoming election (<code>primary2006</code>), and whether the voter had voted in the previous election (<code>primary2004</code>). Other explanatory variables—year of the voter’s birth, sex, and household size—were included to investigate possible effects.</p>
<p>It’s easy to imagine that whether a person voted in <code>primary2004</code> has a role in determining whether the person voted in <code>primary2006</code>, but do the experimental <code>messages</code> sent out before the 2006 primary also play a role? To see this, we can model <code>primary2006</code> by <code>primary2004</code> and <code>messages</code>.</p>
<div id="tbl-go-vote-preview" class="quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-go-vote-preview-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;11.1: The <code>Go_vote</code> data frame.
</figcaption>
<div aria-describedby="tbl-go-vote-preview-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell" data-and_so_on="... for 305,866 rows altogether.">
<div class="cell-output-display">
<div style="font-family: Monospace;">
<table class="lightable-minimal table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">sex</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">yearofbirth</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">primary2004</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">messages</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">primary2006</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">hhsize</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">male</td>
<td style="text-align: right;">1941</td>
<td style="text-align: left;">abstained</td>
<td style="text-align: left;">Civic Duty</td>
<td style="text-align: left;">abstained</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">female</td>
<td style="text-align: right;">1947</td>
<td style="text-align: left;">abstained</td>
<td style="text-align: left;">Civic Duty</td>
<td style="text-align: left;">abstained</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">male</td>
<td style="text-align: right;">1951</td>
<td style="text-align: left;">abstained</td>
<td style="text-align: left;">Hawthorne</td>
<td style="text-align: left;">voted</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">female</td>
<td style="text-align: right;">1950</td>
<td style="text-align: left;">abstained</td>
<td style="text-align: left;">Hawthorne</td>
<td style="text-align: left;">voted</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">female</td>
<td style="text-align: right;">1982</td>
<td style="text-align: left;">abstained</td>
<td style="text-align: left;">Hawthorne</td>
<td style="text-align: left;">voted</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">male</td>
<td style="text-align: right;">1981</td>
<td style="text-align: left;">abstained</td>
<td style="text-align: left;">Control</td>
<td style="text-align: left;">abstained</td>
<td style="text-align: right;">3</td>
</tr>
</tbody>
</table>

<span style="font-style: italic;">&nbsp; &nbsp; &nbsp; ... for 305,866 rows altogether.</span>
</div>

</div>
</div>
</div>
</figure>
</div>
<p>However, as you can see in <a href="#tbl-go-vote-preview" class="quarto-xref">Table&nbsp;<span>11.1</span></a>, both <code>primary2006</code> and <code>primary2004</code> are categorical. Using a categorical variable in an explanatory role is perfectly fine. But in regression modeling, the response variable must be <em>quantitative</em>. To conform with this requirement, we will create a version of <code>primary2006</code> that consists of zeros and ones, with a one indicating the person voted in 2006. Data wrangling with <code>mutate()</code> and the <code>zero_one()</code> function can do this:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>Go_vote <span class="ot">&lt;-</span> Go_vote <span class="sc">|&gt;</span> </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">voted2006 =</span> <span class="fu">zero_one</span>(primary2006, <span class="at">one =</span> <span class="st">"voted"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>After this bit of wrangling, <code>Go_vote</code> has an additional column:</p>
<div class="cell" data-and_so_on="... for 305,866 voters altogether">
<div class="cell-output-display">
<table data-quarto-postprocess="true" class="table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">sex</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">yearofbirth</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">primary2004</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">messages</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">primary2006</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">hhsize</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">voted2006</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">female</td>
<td style="text-align: right;">1965</td>
<td style="text-align: left;">abstained</td>
<td style="text-align: left;">Control</td>
<td style="text-align: left;">abstained</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: left;">male</td>
<td style="text-align: right;">1944</td>
<td style="text-align: left;">voted</td>
<td style="text-align: left;">Neighbors</td>
<td style="text-align: left;">voted</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">female</td>
<td style="text-align: right;">1952</td>
<td style="text-align: left;">voted</td>
<td style="text-align: left;">Civic Duty</td>
<td style="text-align: left;">voted</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">female</td>
<td style="text-align: right;">1947</td>
<td style="text-align: left;">voted</td>
<td style="text-align: left;">Neighbors</td>
<td style="text-align: left;">abstained</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">female</td>
<td style="text-align: right;">1943</td>
<td style="text-align: left;">abstained</td>
<td style="text-align: left;">Control</td>
<td style="text-align: left;">voted</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">female</td>
<td style="text-align: right;">1964</td>
<td style="text-align: left;">voted</td>
<td style="text-align: left;">Civic Duty</td>
<td style="text-align: left;">abstained</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">male</td>
<td style="text-align: right;">1970</td>
<td style="text-align: left;">abstained</td>
<td style="text-align: left;">Hawthorne</td>
<td style="text-align: left;">voted</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">female</td>
<td style="text-align: right;">1969</td>
<td style="text-align: left;">abstained</td>
<td style="text-align: left;">Hawthorne</td>
<td style="text-align: left;">abstained</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>No information is lost in this conversion; <code>voted2006</code> is always 1 when the person voted in 2006 and always 0 otherwise. Since <code>voted2006</code> is numerical, it can play the role of the response variable in regression modeling.</p>
<p>For reference, here are the means of the zero-one variable <code>voted2006</code> for each of eight combinations of explanatory variable levels: four postcard messages times the two values of <code>primary2004</code>. Note that <code>voted2006</code> is a zero-one variable; the means will be the proportion of 1s. That is, the mean of <code>voted2006</code> is the <em>proportion</em> of voters who voted in 2006.</p>
<div class="cell page-columns page-full" data-digits="2">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>Go_vote <span class="sc">|&gt;</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">vote_proportion =</span> <span class="fu">mean</span>(voted2006),</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">.by =</span> <span class="fu">c</span>(messages, primary2004)) <span class="sc">|&gt;</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(messages, primary2004)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div style="font-family: Monospace;">
<table class="lightable-minimal table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">messages</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">primary2004</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">vote_proportion</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Control</td>
<td style="text-align: left;">abstained</td>
<td style="text-align: right;">0.24</td>
</tr>
<tr class="even">
<td style="text-align: left;">Control</td>
<td style="text-align: left;">voted</td>
<td style="text-align: right;">0.39</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Civic Duty</td>
<td style="text-align: left;">abstained</td>
<td style="text-align: right;">0.26</td>
</tr>
<tr class="even">
<td style="text-align: left;">Civic Duty</td>
<td style="text-align: left;">voted</td>
<td style="text-align: right;">0.40</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hawthorne</td>
<td style="text-align: left;">abstained</td>
<td style="text-align: right;">0.26</td>
</tr>
<tr class="even">
<td style="text-align: left;">Hawthorne</td>
<td style="text-align: left;">voted</td>
<td style="text-align: right;">0.41</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Neighbors</td>
<td style="text-align: left;">abstained</td>
<td style="text-align: right;">0.31</td>
</tr>
<tr class="even">
<td style="text-align: left;">Neighbors</td>
<td style="text-align: left;">voted</td>
<td style="text-align: right;">0.48</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>For each kind of message, people who voted in 2004 were likelier to vote in 2006. For instance, the non-2004 voter in the control group had a turnout of 23.7%, whereas the people in the control group who did vote in 2004 had a 38.6% turnout.</p>
<p>Similar information is presented more compactly by the coefficients for a basic model:</p>
<div class="cell page-columns page-full">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>Go_vote <span class="sc">|&gt;</span> </span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model_train</span>(voted2006 <span class="sc">~</span> messages <span class="sc">+</span> primary2004, <span class="at">family =</span> <span class="st">"lm"</span>) <span class="sc">|&gt;</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">conf_interval</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div style="font-family: Monospace;">
<table class="lightable-minimal table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">term</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">.lwr</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">.coef</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">.upr</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">0.2330897</td>
<td style="text-align: right;">0.2355256</td>
<td style="text-align: right;">0.2379614</td>
</tr>
<tr class="even">
<td style="text-align: left;">messagesCivic Duty</td>
<td style="text-align: right;">0.0130218</td>
<td style="text-align: right;">0.0180357</td>
<td style="text-align: right;">0.0230496</td>
</tr>
<tr class="odd">
<td style="text-align: left;">messagesHawthorne</td>
<td style="text-align: right;">0.0202803</td>
<td style="text-align: right;">0.0252950</td>
<td style="text-align: right;">0.0303096</td>
</tr>
<tr class="even">
<td style="text-align: left;">messagesNeighbors</td>
<td style="text-align: right;">0.0753294</td>
<td style="text-align: right;">0.0803442</td>
<td style="text-align: right;">0.0853591</td>
</tr>
<tr class="odd">
<td style="text-align: left;">primary2004voted</td>
<td style="text-align: right;">0.1493516</td>
<td style="text-align: right;">0.1526525</td>
<td style="text-align: right;">0.1559534</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="page-columns page-full"><p>It takes a little practice to learn to interpret coefficients. Let’s start with the <code>messages</code> coefficients. Notice that there is a coefficient for each of the levels of <code>messages</code>, with “Control” as the reference level. According to the model, 23.6% of the control group who did not vote in 2004 turned out for the 2006 election. The <code>primary2004voted</code> coefficient tells us that people who voted in 2004 were 15.3 percentage points more likely to vote in 2006 than the 2004 abstainers. </p><div class="no-row-height column-margin column-container"><span class="margin-aside">We will discuss the difference between “percent” and “percentage point” in Lesson <a href="L21-Measuring-and-accumulating-risk.html" class="quarto-xref"><span>21</span></a>. In brief: “percent” refers to a <em>fraction</em> while “percentage point” is a <em>change in a fraction</em>.</span></div></div>
<p>Each non-control postcard had a higher voting percentage than the control group. The manipulative “Neighbors” post-card shows an eight percentage point increase in voting, while the “Civic Duty” and “Hawthorne” post-cards show smaller changes of about two percentage points each.</p>
</div></div></section>
<section id="tradition-and-correlation" class="level2">
<h2 class="anchored" data-anchor-id="tradition-and-correlation">Tradition and “correlation”</h2>
<p>The reader who has already encountered statistics may be familiar with the word “<strong>correlation</strong>,” now an everyday term used as a synonym for “relationship.” “<strong>Correlation coefficient</strong>” refers to a numerical summary of data invented almost 150 years ago. Since the correlation coefficient emerged very early in the history of statistics, it is understandably treated with respect by traditional textbooks.</p>
<p>We don’t use correlation coefficients in these <em>Lessons</em>. As might be expected for such an early invention, they describe only the simplest relationships. Instead, the regression models introduced in this Lesson enable us to avoid over-simplifications when extracting information from data.</p>


<div class="hidden" aria-hidden="true">
<span class="glightbox-desc lightbox-desc-1">Straight-line function</span>
<span class="glightbox-desc lightbox-desc-2">Sigmoidal function</span>
<span class="glightbox-desc lightbox-desc-3">Discrete-input function</span>
<span class="glightbox-desc lightbox-desc-4">Figure&nbsp;11.2&nbsp;(a): Sloping band</span>
<span class="glightbox-desc lightbox-desc-5">Figure&nbsp;11.2&nbsp;(b): Sigmoid band</span>
<span class="glightbox-desc lightbox-desc-6">Figure&nbsp;11.2&nbsp;(c): Groupwise intervals</span>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./L10-Model-patterns.html" class="pagination-link  aria-label=" &lt;span="" patterns&lt;="" span&gt;"="">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Model patterns</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./L12-Adjustment.html" class="pagination-link" aria-label="<span class='chapter-number'>12</span>&nbsp; <span class='chapter-title'>Adjustment</span>">
        <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Adjustment</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/dtkaplan/Lessons-in-statistical-thinking/blob/main/L11-Regression.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li></ul></div></div></div></footer><script>var lightboxQuarto = GLightbox({"descPosition":"bottom","openEffect":"zoom","selector":".lightbox","closeEffect":"zoom","loop":false});
window.onload = () => {
  lightboxQuarto.on('slide_before_load', (data) => {
    const { slideIndex, slideNode, slideConfig, player, trigger } = data;
    const href = trigger.getAttribute('href');
    if (href !== null) {
      const imgEl = window.document.querySelector(`a[href="${href}"] img`);
      if (imgEl !== null) {
        const srcAttr = imgEl.getAttribute("src");
        if (srcAttr && srcAttr.startsWith("data:")) {
          slideConfig.href = srcAttr;
        }
      }
    } 
  });

  lightboxQuarto.on('slide_after_load', (data) => {
    const { slideIndex, slideNode, slideConfig, player, trigger } = data;
    if (window.Quarto?.typesetMath) {
      window.Quarto.typesetMath(slideNode);
    }
  });

};
          </script>




</body></html>